package my.pnr.digital.v2;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.location.*;
import android.net.Uri;
import android.os.*;
import android.provider.MediaStore;
import android.text.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.*;

/** Native Android screens. This activity does not embed web content. */
public class MainActivity extends Activity {
    final int INK=Color.rgb(16,35,63), MUTED=Color.rgb(85,105,126), BG=Color.rgb(243,247,251), LIME=Color.rgb(192,241,235), WHITE=Color.WHITE, LINE=Color.rgb(220,230,239), RED=Color.rgb(180,45,67), TEAL=Color.rgb(0,119,116), BLUE=Color.rgb(46,91,181), AMBER=Color.rgb(147,89,12);
    final ExecutorService executor=Executors.newSingleThreadExecutor();
    final Handler handler=new Handler(Looper.getMainLooper());
    NativeStore store;JSONObject user=new JSONObject(),master=new JSONObject(),districts=new JSONObject(),draft=new JSONObject();
    JSONArray records=new JSONArray(),pests=new JSONArray(),photos=new JSONArray();
    String token="",uid="",query="",period="all",stateFilter="",screen="home",editingId="";JSONArray retainedImages=new JSONArray();
    int epoch=0,step=0,page=0;boolean posting=false,hasLoaded=false;LinearLayout root,body,nav,header;FrameLayout content;TextView status;ProgressBar loading;LinearLayout operationOverlay;
    final Map<String,EditText> fields=new LinkedHashMap<>();
    Uri cameraUri;LocationListener locationListener; byte[] exportBytes;
    final DashboardModule dashboard=new DashboardModule(this);
    final RecordExplorer explorer=new RecordExplorer(this);
    RpwModule rpw; boolean photoProcessing=false, dataLoading=false; int activeRequests=0; String cacheTime=""; Runnable locationTimeout; boolean preview=false;int taskPage=0;
    interface Success {void accept(JSONObject data);}
    int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    JSONObject obj(Object... pairs){JSONObject o=new JSONObject();for(int i=0;i<pairs.length;i+=2)put(o,pairs[i].toString(),pairs[i+1]);return o;}
    void put(JSONObject o,String key,Object value){try{o.put(key,value);}catch(JSONException ignored){}}
    JSONObject object(JSONObject o,String key){Object x=o.opt(key);if(x instanceof JSONObject)return (JSONObject)x;try{return new JSONObject(String.valueOf(x));}catch(Exception e){return new JSONObject();}}
    JSONArray array(JSONObject o,String key){JSONArray a=o.optJSONArray(key);return a==null?new JSONArray():a;}
    String date(){return new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());}
    String number(double x){return String.format(Locale.US,"%,.2f",x);}
    GradientDrawable shape(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    TextView text(String value,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);t.setFontFeatureSettings("tnum");t.setTypeface(android.graphics.Typeface.create(bold?"sans-serif-medium":"sans-serif",0));t.setLineSpacing(dp(3),1);return t;}
    LinearLayout column(){LinearLayout c=new LinearLayout(this);c.setOrientation(1);return c;}
    LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);return r;}
    void gap(LinearLayout c,int height){Space s=new Space(this);c.addView(s,new LinearLayout.LayoutParams(1,dp(height)));}
    Button button(String label,boolean primary,Runnable action){Button b=new Button(this);b.setText(label);b.setTextSize(14);b.setAllCaps(false);b.setTextColor(primary?WHITE:INK);b.setBackground(new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(0x22007774),shape(primary?TEAL:LINE,14),null));b.setMinHeight(dp(48));b.setPadding(dp(16),dp(8),dp(16),dp(8));b.setOnClickListener(v->{if(posting||photoProcessing){toast("Sila tunggu proses semasa selesai.");return;}action.run();});return b;}
    void addButton(LinearLayout c,String label,boolean primary,Runnable action){Button b=button(label,primary,action);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.topMargin=dp(10);c.addView(b,lp);}
    LinearLayout card(LinearLayout parent,int color){LinearLayout c=column();c.setPadding(dp(20),dp(20),dp(20),dp(20));GradientDrawable surface=shape(color,20);if(color==WHITE)surface.setStroke(dp(1),LINE);c.setBackground(surface);c.setElevation(dp(color==WHITE?1:0));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(14);parent.addView(c,lp);return c;}
    void toast(String message){Toast.makeText(this,message,Toast.LENGTH_LONG).show();}
    void alert(String title,String message){new AlertDialog.Builder(this).setTitle(title).setMessage(message).setPositiveButton("OK",null).show();}
    void busy(boolean value){activeRequests=Math.max(0,activeRequests+(value?1:-1));if(loading!=null)loading.setVisibility(activeRequests>0?View.VISIBLE:View.GONE);if(content!=null){if(value&&posting&&operationOverlay==null){operationOverlay=column();operationOverlay.setGravity(Gravity.CENTER);operationOverlay.setBackgroundColor(0xF2F3F7FB);operationOverlay.setClickable(true);operationOverlay.setFocusable(true);ProgressBar spinner=new ProgressBar(this);spinner.setIndeterminateTintList(android.content.res.ColorStateList.valueOf(TEAL));operationOverlay.addView(spinner,new LinearLayout.LayoutParams(dp(48),dp(48)));gap(operationOverlay,16);operationOverlay.addView(text("Sedang memproses…",18,INK,true));operationOverlay.addView(text("Sila tunggu respons pelayan.",14,MUTED,false));content.addView(operationOverlay,new FrameLayout.LayoutParams(-1,-1));}if(!value&&operationOverlay!=null){content.removeView(operationOverlay);operationOverlay=null;}}}
    boolean online(){android.net.ConnectivityManager cm=(android.net.ConnectivityManager)getSystemService(CONNECTIVITY_SERVICE);android.net.NetworkCapabilities caps=cm.getNetworkCapabilities(cm.getActiveNetwork());return caps!=null&&caps.hasCapability(android.net.NetworkCapabilities.NET_CAPABILITY_INTERNET);}
    void request(String route,JSONObject payload,Success success){
        if(preview){if(route.equals("data/my-tasks")||route.equals("data/pending"))success.accept(obj("rows",new JSONArray()));else toast("Paparan ujian sahaja.");return;}
        final int generation=epoch;final String auth=token,account=uid;
        if(!online()){posting=false;alert("Tiada sambungan","Draf kekal di telefon. Sambung internet untuk tindakan ini.");return;}
        busy(true);
        executor.execute(()->{try{JSONObject result=ApiClient.post(route,payload,auth,account);handler.post(()->{busy(false);if(isDestroyed()||isFinishing()||generation!=epoch||!uid.equals(account))return;success.accept(result);});}catch(Exception e){handler.post(()->{busy(false);if(isDestroyed()||isFinishing()||generation!=epoch||!uid.equals(account))return;posting=false;if(route.equals("data/submit-bancian")&&e instanceof ApiClient.ApiError&&((ApiClient.ApiError)e).status==400){draft.remove("_pendingPayload");saveDraft(false);if(screen.equals("form"))redrawForm();}if(e instanceof ApiClient.ApiError&&((ApiClient.ApiError)e).status==401&&!route.equals("auth/login")){store.remove("session");token="";showLogin();toast("Sesi tamat. Draf dikekalkan; log masuk semula.");}else alert("Belum berjaya",e instanceof ApiClient.ApiError?e.getMessage():"Semak sambungan internet. Penghantaran belum disahkan kekal dalam Borang; gunakan Semak & hantar semula.");});}});
    }
    @Override public void onCreate(Bundle saved){super.onCreate(saved);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(WHITE);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);store=new NativeStore(this);rpw=new RpwModule(this);try(InputStream in=getAssets().open("districts.json")){districts=new JSONObject(new String(read(in),"UTF-8"));}catch(Exception ignored){}
        try{JSONObject session=new JSONObject(store.get("session"));user=session.getJSONObject("user");uid=session.getString("uid");token=user.optString("token");}catch(Exception ignored){}
        root=column();root.setBackgroundColor(BG);if(Build.VERSION.SDK_INT>=30)root.setOnApplyWindowInsetsListener((view,insets)->{Insets bars=insets.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.ime());view.setPadding(bars.left,bars.top,bars.right,bars.bottom);return insets;});setContentView(root);
        preview=(getApplicationInfo().flags&android.content.pm.ApplicationInfo.FLAG_DEBUGGABLE)!=0&&getIntent().getBooleanExtra("preview",false);
        if(preview){uid="preview";token="preview";user=obj("name","Pegawai Lapangan","role","ADMIN","state","ALL");hasLoaded=true;records=new JSONArray();String[] sampleCrops={"Padi","Mangga","Kelapa","Jagung","Pisang","Cili"};for(int month=0;month<6;month++){Calendar cal=Calendar.getInstance();cal.set(Calendar.DAY_OF_MONTH,8);cal.add(Calendar.MONTH,-month);String stamp=new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(cal.getTime());for(int j=0;j<3+(month*7)%11;j++){String crop=sampleCrops[j%6];records.put(obj("id","DEMO-"+month+"-"+j,"tn",crop,"l","Plot contoh "+(j+1),"d","KUALA SELANGOR","n","SELANGOR","t",stamp,"lt",4.5+j,"ls",0.3+j*.12,"pg","Pegawai contoh","p",obj(j%2==0?"Ulat batang":"Lalat buah",0.3+j*.12),"st","DISAHKAN"));}}dashboard.tab=getIntent().getStringExtra("tab")==null?"Ringkasan":getIntent().getStringExtra("tab");explorer.table=!getIntent().getBooleanExtra("cards",false);master=obj("Bijirin",obj("Padi",new JSONArray().put("Ulat batang")));rpw.preview();show(getIntent().getStringExtra("screen")==null?"home":getIntent().getStringExtra("screen"));return;}
        if(token.isEmpty())showLogin();else{restoreCache();String target=saved==null?"home":saved.getString("screen","home");step=saved==null?0:saved.getInt("step",0);query=saved==null?"":saved.getString("query","");period=saved==null?"all":saved.getString("period","all");stateFilter=saved==null?"":saved.getString("stateFilter","");if(saved!=null){dashboard.tab=saved.getString("analysisTab","Ringkasan");dashboard.district=saved.getString("district","");dashboard.crop=saved.getString("crop","");dashboard.pest=saved.getString("pest","");explorer.searchField=saved.getString("searchField","");explorer.sort=saved.getString("recordSort","Tarikh terkini");explorer.table=saved.getBoolean("recordTable",true);}if(saved!=null&&saved.getString("cameraUri")!=null)cameraUri=Uri.parse(saved.getString("cameraUri"));if(saved!=null&&saved.getBoolean("exportPending")){String csv=store.get("export_"+uid);if(!csv.isEmpty())exportBytes=csv.startsWith("B64:")?android.util.Base64.decode(csv.substring(4),android.util.Base64.NO_WRAP):csv.getBytes(java.nio.charset.StandardCharsets.UTF_8);}show(target);loadData();loadMaster();}
    }
    void shell(boolean logged){operationOverlay=null;root.removeAllViews();header=column();header.setPadding(dp(22),dp(12),dp(22),dp(10));root.addView(header);loading=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);loading.setIndeterminate(true);loading.setProgressTintList(android.content.res.ColorStateList.valueOf(TEAL));loading.setVisibility(activeRequests>0?View.VISIBLE:View.GONE);root.addView(loading,new LinearLayout.LayoutParams(-1,dp(3)));content=new FrameLayout(this);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));if(logged){nav=row();nav.setPadding(dp(8),dp(8),dp(8),dp(8));nav.setBackgroundColor(INK);root.addView(nav);String[] names={"Utama","Rekod","Bancian","Tugasan","Akaun"},keys={"home","records","form","tasks","profile"};int[] icons={R.drawable.ic_home,R.drawable.ic_records,R.drawable.ic_add,R.drawable.ic_tasks,R.drawable.ic_account};for(int i=0;i<names.length;i++){final String dest=keys[i];LinearLayout item=column();item.setGravity(Gravity.CENTER);item.setPadding(dp(2),dp(8),dp(2),dp(8));item.setBackground(shape(screen.equals(dest)?TEAL:INK,16));ImageView icon=new ImageView(this);icon.setImageResource(icons[i]);icon.setColorFilter(screen.equals(dest)?WHITE:Color.rgb(163,189,210));item.addView(icon,new LinearLayout.LayoutParams(dp(23),dp(23)));TextView label=text(names[i],11,screen.equals(dest)?WHITE:Color.rgb(163,189,210),screen.equals(dest));label.setGravity(Gravity.CENTER);item.addView(label);item.setContentDescription(names[i]);item.setFocusable(true);item.setOnClickListener(v->navigate(dest));nav.addView(item,new LinearLayout.LayoutParams(0,-2,1));}}}
    LinearLayout scroller(){ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setClipToPadding(false);body=column();body.setPadding(dp(18),dp(8),dp(18),dp(24));scroll.addView(body);content.addView(scroll,new FrameLayout.LayoutParams(-1,-1));return body;}
    void heading(String eyebrow,String title,String subtitle){TextView badge=text((preview?"DEMO · DATA CONTOH  /  ":"")+eyebrow.toUpperCase(Locale.ROOT),11,TEAL,true);badge.setLetterSpacing(.12f);header.addView(badge);gap(header,6);header.addView(text(title,28,INK,true));if(!subtitle.isEmpty()){gap(header,4);header.addView(text(subtitle,14,MUTED,false));}}
    void showLogin(){epoch++;screen="login";shell(false);header.setPadding(dp(28),dp(24),dp(28),dp(12));heading("PNR DIGITAL • ANDROID","Bancian lebih mudah.","Biosekuriti tumbuhan · Jabatan Pertanian");LinearLayout c=scroller();LinearLayout hero=card(c,INK);hero.addView(text("Data lapangan.\nTindakan bermakna.",30,LIME,true));gap(hero,12);hero.addView(text("Aplikasi pemantauan perosak tanaman",15,WHITE,false));gap(c,12);c.addView(text("Selamat kembali",24,INK,true));gap(c,6);c.addView(text("Gunakan akaun sistem PNR v2 anda.",14,MUTED,false));EditText id=input(c,"ID pengguna","",false);id.setAutofillHints(View.AUTOFILL_HINT_USERNAME);EditText pass=input(c,"Kata laluan","",false);pass.setInputType(129);pass.setAutofillHints(View.AUTOFILL_HINT_PASSWORD);addButton(c,"Log masuk",true,()->{String u=id.getText().toString().trim(),p=pass.getText().toString();if(u.isEmpty()||p.isEmpty()){toast("Isi ID dan kata laluan.");return;}posting=true;request("auth/login",obj("u",u,"p",p),result->{posting=false;uid=result.optString("uid",u);user=result;token=result.optString("token");try{store.put("session",obj("uid",uid,"user",user).toString());}catch(Exception e){toast("Sesi tidak dapat disimpan. Log masuk diperlukan apabila aplikasi dibuka semula.");}restoreCache();show("home");loadData();loadMaster();});});addButton(c,"Daftar / bantuan akaun",false,()->external(ApiClient.ORIGIN+"/"));if((getApplicationInfo().flags&android.content.pm.ApplicationInfo.FLAG_DEBUGGABLE)!=0)addButton(c,"Lihat demo reka bentuk",false,()->{startActivity(new Intent(this,MainActivity.class).putExtra("preview",true));});}
    EditText input(LinearLayout c,String label,String value,boolean numeric){gap(c,12);c.addView(text(label,14,INK,true));gap(c,6);EditText e=new EditText(this);e.setText(value);e.setTextSize(16);e.setTextColor(INK);e.setHintTextColor(MUTED);e.setHint(label);e.setSingleLine(true);e.setPadding(dp(14),dp(10),dp(14),dp(10));GradientDrawable bg=shape(WHITE,12);bg.setStroke(dp(1),LINE);e.setBackground(bg);if(numeric)e.setInputType(8194);c.addView(e,new LinearLayout.LayoutParams(-1,dp(52)));return e;}
    void navigate(String destination){if(posting||photoProcessing){toast("Tunggu proses selesai dahulu.");return;}if(screen.equals("form")&&!destination.equals("form")){collect();saveDraft(false);}show(destination);}
    void show(String target){if(dashboard.filterSheet!=null){dashboard.filterSheet.dismiss();dashboard.filterSheet=null;}epoch++;screen=target;shell(true);if(target.equals("home"))home();else if(target.equals("records"))recordScreen();else if(target.equals("form"))form();else if(target.equals("tasks"))tasks(false);else if(target.equals("rpw"))rpw.show();else profile();if(android.animation.ValueAnimator.areAnimatorsEnabled()){content.setAlpha(0f);content.setTranslationY(dp(10));content.animate().alpha(1f).translationY(0).setDuration(240).setInterpolator(new android.view.animation.DecelerateInterpolator()).start();}}
    void restoreCache(){try{JSONObject cached=new JSONObject(store.get("analytics_"+uid));records=array(cached,"records");cacheTime=cached.optString("savedAt");hasLoaded=true;}catch(Exception ignored){}try{master=new JSONObject(store.get("master_"+uid));}catch(Exception ignored){}}
    void cache(String name,JSONObject value){final String account=uid;final String snapshot=value.toString();executor.execute(()->{try{store.put(name+"_"+account,snapshot);}catch(Exception ignored){handler.post(()->toast("Salinan offline tidak dapat disimpan."));}});}
    void loadData(){if(preview||dataLoading)return;if(!online()){toast(hasLoaded?"Memaparkan salinan terakhir di telefon.":"Tiada salinan offline. Muatkan sekali dengan internet.");return;}dataLoading=true;busy(true);final String account=uid,auth=token;
        executor.execute(()->{try{JSONObject result=ApiClient.post("data/analytics",obj("state",user.optString("state","ALL")),auth,account);handler.post(()->{dataLoading=false;busy(false);if(isDestroyed()||!uid.equals(account))return;records=array(result,"records");hasLoaded=true;cacheTime=new SimpleDateFormat("dd MMM, HH:mm",new Locale("ms","MY")).format(new Date());cache("analytics",obj("records",records,"savedAt",cacheTime));if(screen.equals("home")||screen.equals("records"))show(screen);});}catch(Exception e){handler.post(()->{dataLoading=false;busy(false);if(!isDestroyed()&&uid.equals(account))toast("Data belum dikemas kini. Salinan terakhir dikekalkan.");});}});
    }
    void loadMaster(){if(preview||!online())return;final String auth=token,account=uid;executor.execute(()->{try{JSONObject result=ApiClient.post("data/master-tanaman",obj(),auth,account);handler.post(()->{if(isDestroyed()||!uid.equals(account))return;master=object(result,"data");cache("master",master);if(screen.equals("form")&&step==1){collect();redrawForm();}});}catch(Exception e){handler.post(()->{if(!isDestroyed()&&uid.equals(account)&&master.length()==0)toast("Rujukan tanaman belum tersedia. Sambung internet dan cuba lagi.");});}});}
    void syncNote(LinearLayout c){TextView note=text((online()?"DALAM TALIAN":"OFFLINE")+"  ·  "+(cacheTime.isEmpty()?"Data belum disegerakkan":"Salinan "+cacheTime),12,MUTED,false);c.addView(note);gap(c,16);}
    void section(LinearLayout c,String title,String subtitle){gap(c,12);c.addView(text(title,20,INK,true));if(!subtitle.isEmpty())c.addView(text(subtitle,13,MUTED,false));gap(c,14);}
    void module(LinearLayout c,String code,String title,String description,int color,Runnable action){LinearLayout tile=card(c,WHITE);LinearLayout line=row();TextView mark=text(code,13,color,true);mark.setGravity(Gravity.CENTER);mark.setBackground(shape(BG,14));line.addView(mark,new LinearLayout.LayoutParams(dp(52),dp(52)));LinearLayout words=column();words.setPadding(dp(14),0,dp(8),0);words.addView(text(title,18,INK,true));words.addView(text(description,13,MUTED,false));line.addView(words,new LinearLayout.LayoutParams(0,-2,1));line.addView(text("›",26,color,true));tile.addView(line);tile.setOnClickListener(v->action.run());tile.setFocusable(true);tile.setContentDescription(title+". "+description);}
    void steps(LinearLayout c){LinearLayout line=row();String[] labels={"Lokasi","Tanaman","Perosak","Semakan"};for(int i=0;i<4;i++){LinearLayout item=column();item.setGravity(Gravity.CENTER);TextView n=text(i<step?"✓":String.valueOf(i+1),14,i<=step?WHITE:MUTED,true);n.setGravity(Gravity.CENTER);n.setBackground(shape(i<=step?TEAL:LINE,20));item.addView(n,new LinearLayout.LayoutParams(dp(34),dp(34)));gap(item,5);item.addView(text(labels[i],11,i==step?TEAL:MUTED,i==step));line.addView(item,new LinearLayout.LayoutParams(0,-2,1));}c.addView(line);gap(c,20);}

    List<JSONObject> filtered(){List<JSONObject> result=new ArrayList<>();String now=date();for(int i=0;i<records.length();i++){JSONObject r=records.optJSONObject(i);if(r==null)continue;if(!dashboard.matches(r))continue;String t=r.optString("t");if(period.equals("month")&&!t.startsWith(now.substring(0,7)))continue;if(period.equals("year")&&!t.startsWith(now.substring(0,4)))continue;if(!stateFilter.isEmpty()&&!stateFilter.equals(r.optString("n")))continue;if(screen.equals("records")&&!query.isEmpty()&&!RecordQuery.matches(r,query,explorer.searchField))continue;result.add(r);}if(screen.equals("records"))result.sort(RecordQuery.order(explorer.sort));return result;}
    void filters(LinearLayout c){LinearLayout line=row();String[] values={"all","month","year"},labels={"Semua","Bulan ini","Tahun ini"};for(int i=0;i<values.length;i++){final String val=values[i];Button b=button(labels[i],period.equals(val),()->{period=val;page=0;show(screen);});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.rightMargin=dp(5);line.addView(b,lp);}c.addView(line);gap(c,12);if(user.optString("state").equals("ALL")){Button state=button(stateFilter.isEmpty()?"Semua negeri  ▾":stateFilter+"  ▾",false,()->{TreeSet<String> names=new TreeSet<>();for(int i=0;i<records.length();i++)names.add(records.optJSONObject(i).optString("n"));List<String> all=new ArrayList<>();all.add("Semua negeri");all.addAll(names);new AlertDialog.Builder(this).setTitle("Negeri").setItems(all.toArray(new String[0]),(d,n)->{stateFilter=n==0?"":all.get(n);dashboard.district="";page=0;show(screen);}).show();});c.addView(state);gap(c,12);}dashboard.filters(c);}
    void quickTile(LinearLayout row,String symbol,String title,String subtitle,int color,Runnable action){
        LinearLayout tile=column();tile.setPadding(dp(17),dp(17),dp(17),dp(18));GradientDrawable surface=shape(WHITE,20);surface.setStroke(dp(1),LINE);tile.setBackground(new android.graphics.drawable.RippleDrawable(android.content.res.ColorStateList.valueOf(0x22007774),surface,null));
        TextView icon=text(symbol,12,color,true);icon.setGravity(Gravity.CENTER);icon.setBackground(shape(color==TEAL?LIME:BG,12));tile.addView(icon,new LinearLayout.LayoutParams(dp(44),dp(36)));gap(tile,14);tile.addView(text(title,18,INK,true));gap(tile,3);tile.addView(text(subtitle,12,MUTED,false));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-1,1);lp.rightMargin=dp(row.getChildCount()==0?10:0);row.addView(tile,lp);tile.setFocusable(true);tile.setContentDescription(title+". "+subtitle);tile.setOnClickListener(v->action.run());
    }
    void home(){dashboard.show();}
    void recordScreen(){explorer.show();}
    void renderRecords(LinearLayout list){list.removeAllViews();List<JSONObject> selected=filtered();list.addView(text(selected.size()+" rekod sepadan",12,MUTED,false));gap(list,10);if(selected.isEmpty()){list.addView(text("Tiada rekod. Ubah tapisan atau muatkan data.",16,MUTED,false));return;}int start=page*20;if(start>=selected.size()){page=0;start=0;}for(int i=start;i<Math.min(start+20,selected.size());i++){JSONObject r=selected.get(i);LinearLayout card=card(list,WHITE);card.addView(text("DISAHKAN  ·  "+r.optString("n"),11,TEAL,true));gap(card,10);card.addView(text(r.optString("tn","Tanaman"),21,INK,true));gap(card,5);card.addView(text(r.optString("l")+" · "+r.optString("d"),14,MUTED,false));gap(card,12);LinearLayout meta=row();meta.addView(text(r.optString("t"),12,MUTED,false),new LinearLayout.LayoutParams(0,-2,1));TextView damage=text(number(r.optDouble("ls",0))+" ha\nserangan",12,RED,true);damage.setGravity(Gravity.END);meta.addView(damage);card.addView(meta);card.setOnClickListener(v->detail(r,null,false));card.setFocusable(true);card.setContentDescription(r.optString("tn")+", "+r.optString("l")+", buka butiran");}LinearLayout pagination=row();Button prev=button("‹ Sebelum",false,()->{page--;renderRecords(list);});prev.setEnabled(page>0);pagination.addView(prev,new LinearLayout.LayoutParams(0,dp(48),1));Button next=button("Seterusnya ›",false,()->{page++;renderRecords(list);});next.setEnabled((page+1)*20<selected.size());pagination.addView(next,new LinearLayout.LayoutParams(0,dp(48),1));list.addView(pagination);}
    JSONObject normalized(JSONObject row){JSONArray a=array(row,"data");return obj("id",row.optString("row"),"t",a.optString(3),"n",a.optString(4),"d",a.optString(5),"l",a.optString(6),"c",a.optString(7),"kt",a.optString(8),"tn",a.optString(9),"vr",a.optString(10),"um",a.optString(11),"lt",a.optDouble(12,0),"p",a.opt(13),"ps",a.opt(14),"pk",a.opt(15),"s",a.optString(16),"catatan",a.optString(17),"im",a.optString(18),"caption",a.optString(19),"st",a.optString(20),"vb",a.optString(21),"pg",a.optString(1),"em",a.optString(2));}
    boolean supervisor(){return Arrays.asList("ADMIN","PENYELIA").contains(user.optString("role").toUpperCase(Locale.ROOT));}
    void tasks(boolean verify){heading("ALIRAN KERJA",verify?"Pengesahan":"Tugasan saya",verify?"Semak laporan sebelum disahkan":"Draf, laporan baharu dan pembetulan");LinearLayout c=scroller();if(supervisor()){addButton(c,verify?"Lihat tugasan saya":"Semak laporan menunggu",false,()->{epoch++;shell(true);taskPage=0;tasks(!verify);});}if(!verify&&!store.get("draft_"+uid).isEmpty())addButton(c,"Sambung draf di telefon",true,()->show("form"));LinearLayout list=column();c.addView(list);list.addView(text("Memuatkan rekod…",14,MUTED,false));Success render=result->{list.removeAllViews();JSONArray rows=array(result,"rows");taskPage=Math.max(0,Math.min(taskPage,Math.max(0,(rows.length()-1)/20)));list.addView(text(rows.length()+" rekod",14,MUTED,false));gap(list,12);for(int i=taskPage*20;i<Math.min(rows.length(),taskPage*20+20);i++){JSONObject raw=rows.optJSONObject(i);JSONObject r=normalized(raw);LinearLayout card=card(list,WHITE);card.addView(text(r.optString("st","BARU"),12,RED,true));gap(card,7);card.addView(text(r.optString("tn"),18,INK,true));card.addView(text(r.optString("l")+" · "+r.optString("t"),14,MUTED,false));if(!r.optString("vb").isEmpty()){gap(card,8);card.addView(text(r.optString("vb"),14,MUTED,false));}addButton(card,verify?"Semak laporan":"Buka laporan",false,()->detail(r,raw,verify));}if(rows.length()==0){LinearLayout empty=card(list,WHITE);empty.addView(text("Semua selesai",20,INK,true));gap(empty,8);empty.addView(text("Tiada tugasan dalam senarai ini.",15,MUTED,false));}if(rows.length()<=20)return;LinearLayout pages=row();Button prev=button("‹ Sebelum",false,()->{taskPage--;epoch++;shell(true);tasks(verify);});prev.setEnabled(taskPage>0);pages.addView(prev,new LinearLayout.LayoutParams(0,-2,1));Button next=button("Seterusnya ›",false,()->{taskPage++;epoch++;shell(true);tasks(verify);});next.setEnabled((taskPage+1)*20<rows.length());pages.addView(next,new LinearLayout.LayoutParams(0,-2,1));list.addView(pages);};String cacheKey="tasks_"+uid+"_"+verify;if(!online()){try{JSONObject cached=new JSONObject(store.get(cacheKey));render.accept(cached);c.addView(text("Salinan luar talian • tindakan memerlukan internet",13,AMBER,false));}catch(Exception e){list.removeAllViews();list.addView(text("Tugasan belum disimpan. Sambung internet untuk memuatkan senarai.",15,MUTED,false));}return;}request(verify?"data/pending":"data/my-tasks",new JSONObject(),result->{try{store.put(cacheKey,result.toString());}catch(Exception e){toast("Senarai tidak dapat disimpan untuk luar talian.");}render.accept(result);});}
    void detail(JSONObject record,JSONObject raw,boolean verify){final Dialog dialog=new Dialog(this);LinearLayout outer=column();outer.setPadding(dp(22),dp(22),dp(22),dp(22));outer.setBackground(shape(BG,26));ScrollView scroll=new ScrollView(this);LinearLayout c=column();scroll.addView(c);outer.addView(scroll,new LinearLayout.LayoutParams(-1,-1));c.addView(text(record.optString("tn"),25,INK,true));gap(c,5);c.addView(text(record.optString("l"),16,MUTED,false));String[][] values={{"Status",record.optString("st","DISAHKAN")},{"Pegawai",record.optString("pg")},{"Tarikh",record.optString("t")},{"Negeri / daerah",record.optString("n")+" / "+record.optString("d")},{"Luas bertanam",number(record.optDouble("lt",0))+" ha"},{"Varieti / umur",record.optString("vr")+" / "+record.optString("um")},{"Syor kawalan",record.optString("s")},{"Catatan",record.optString("catatan")},{"Log",record.optString("vb")}};for(String[] v:values){gap(c,16);c.addView(text(v[0],12,MUTED,true));c.addView(text(v[1].isEmpty()?"—":v[1],16,INK,false));}JSONObject pests=object(record,"p");Iterator<String> keys=pests.keys();while(keys.hasNext()){String key=keys.next();gap(c,12);c.addView(text(key+" · "+number(pests.optDouble(key,0))+" ha",16,RED,true));}String coord=record.optString("c");if(coord.matches("\\s*-?\\d+(\\.\\d+)?\\s*,\\s*-?\\d+(\\.\\d+)?\\s*"))addButton(c,"Buka lokasi di peta",false,()->external("geo:"+coord.trim()+"?q="+Uri.encode(coord.trim())));String images=record.optString("im");if(images.startsWith("https://"))addButton(c,"Lihat gambar laporan",false,()->external(images.split(",")[0].trim()));
        if(verify&&supervisor()){addButton(c,"Sahkan laporan",true,()->new AlertDialog.Builder(this).setMessage("Sahkan laporan ini?").setPositiveButton("Sahkan",(d,w)->{dialog.dismiss();posting=true;request("data/verify",obj("row",record.optString("id"),"act","APPROVE","name",user.optString("name")),r->{posting=false;toast("Laporan disahkan.");show("tasks");});}).setNegativeButton("Batal",null).show());addButton(c,"Kembalikan untuk pembetulan",false,()->{EditText reason=new EditText(this);reason.setHint("Sebab penolakan");new AlertDialog.Builder(this).setTitle("Sebab pembetulan").setView(reason).setPositiveButton("Hantar",(d,w)->{if(reason.getText().toString().trim().isEmpty()){toast("Sebab diperlukan.");return;}dialog.dismiss();posting=true;request("data/verify",obj("row",record.optString("id"),"act","REJECT","reason",reason.getText().toString(),"name",user.optString("name")),r->{posting=false;toast("Laporan dikembalikan.");show("tasks");});}).setNegativeButton("Batal",null).show();});}
        if(raw!=null&&!verify&&Arrays.asList("DRAF","DITOLAK").contains(record.optString("st")))addButton(c,"Edit dan hantar semula",true,()->{dialog.dismiss();editRecord(record);});addButton(c,"Tutup",false,dialog::dismiss);dialog.setContentView(outer);Window window=dialog.getWindow();if(window!=null){window.setBackgroundDrawableResource(android.R.color.transparent);window.setLayout(-1,(int)(getResources().getDisplayMetrics().heightPixels*.88));window.setGravity(Gravity.BOTTOM);}dialog.show();if(window!=null)window.setLayout(-1,(int)(getResources().getDisplayMetrics().heightPixels*.88));}
    void initDraft(){if(draft.length()>0)return;try{draft=new JSONObject(store.get("draft_"+uid));pests=array(draft,"_pests");photos=array(draft,"_photos");editingId=draft.optString("_editingId");retainedImages=array(draft,"_retained");step=Math.max(0,Math.min(3,draft.optInt("_step",step)));}catch(Exception e){draft=obj("namaPegawai",user.optString("name"),"tarikhBancian",date(),"negeri",user.optString("state").equals("ALL")?"":user.optString("state"));pests=new JSONArray();photos=new JSONArray();editingId="";retainedImages=new JSONArray();}}
    void field(LinearLayout c,String key,String label,boolean numeric){EditText e=input(c,label,draft.optString(key),numeric);fields.put(key,e);}
    void choose(LinearLayout c,String key,String label,List<String> options){field(c,key,label,false);EditText e=fields.get(key);if(!options.isEmpty()){e.setFocusable(false);e.setOnClickListener(v->new AlertDialog.Builder(this).setTitle(label).setItems(options.toArray(new String[0]),(d,n)->{e.setText(options.get(n));collect();if(key.equals("negeri"))put(draft,"daerah","");if(key.equals("kategori"))put(draft,"namaTanaman","");if(key.equals("kategori")||key.equals("namaTanaman")){pests=new JSONArray();put(draft,"_noPest",false);}redrawForm();}).show());}}
    List<String> keys(JSONObject obj){List<String> list=new ArrayList<>();obj.keys().forEachRemaining(list::add);Collections.sort(list);return list;}
    List<String> strings(JSONArray a){List<String> list=new ArrayList<>();for(int i=0;i<a.length();i++)list.add(a.optString(i));return list;}
    void redrawForm(){shell(true);form();}
    void form(){initDraft();fields.clear();if(draft.has("_pendingPayload")){pendingScreen();return;}heading(editingId.isEmpty()?"BANCIAN BAHARU":"PEMBETULAN LAPORAN","Catat pemerhatian","Langkah "+(step+1)+" daripada 4");LinearLayout c=scroller();steps(c);LinearLayout panel=card(c,WHITE);
        if(step==0){panel.addView(text("Di mana bancian dibuat?",22,INK,true));field(panel,"namaPegawai","Nama pegawai *",false);fields.get("namaPegawai").setEnabled(false);field(panel,"email","E-mel *",false);fields.get("email").setInputType(33);field(panel,"tarikhBancian","Tarikh bancian *",false);EditText date=fields.get("tarikhBancian");date.setFocusable(false);date.setOnClickListener(v->{Calendar cal=Calendar.getInstance();DatePickerDialog picker=new DatePickerDialog(this,(x,y,m,d)->date.setText(String.format(Locale.US,"%04d-%02d-%02d",y,m+1,d)),cal.get(Calendar.YEAR),cal.get(Calendar.MONTH),cal.get(Calendar.DAY_OF_MONTH));picker.getDatePicker().setMaxDate(System.currentTimeMillis());picker.show();});choose(panel,"negeri","Negeri *",keys(districts));if(!user.optString("state","ALL").equals("ALL"))fields.get("negeri").setEnabled(false);choose(panel,"daerah","Daerah *",strings(array(districts,draft.optString("negeri"))));field(panel,"lokasi","Lokasi / kebun *",false);field(panel,"koordinat","Koordinat latitud, longitud *",false);fields.get("koordinat").setHint("Contoh: 2.9264, 101.6964");addButton(panel,"Gunakan lokasi telefon",false,this::getLocation);panel.addView(text(draft.has("_gpsAccuracy")?"Ketepatan bacaan GPS terakhir: ±"+Math.round(draft.optDouble("_gpsAccuracy"))+" m. Semak koordinat sebelum hantar.":"Hidupkan lokasi. Koordinat manual tersedia jika kebenaran ditolak.",12,MUTED,false));}
        if(step==1){panel.addView(text("Maklumat tanaman",22,INK,true));if(master.length()==0){panel.addView(text("Rujukan tanaman belum dimuatkan. Anda boleh simpan draf dan muatkan rujukan apabila internet tersedia.",14,AMBER,false));addButton(panel,"Muatkan rujukan tanaman",false,this::loadMaster);}choose(panel,"kategori","Kategori *",keys(master));choose(panel,"namaTanaman","Tanaman *",keys(object(master,draft.optString("kategori"))));field(panel,"varieti","Varieti",false);field(panel,"umurTanaman","Umur tanaman",false);fields.get("umurTanaman").setHint("Contoh: 45 hari");field(panel,"luasBertanam","Luas bertanam (ha) *",true);panel.addView(text("Gunakan hektar. Jangan masukkan bilangan pokok, polibeg atau unit lain.",12,MUTED,false));}
        if(step==2){panel.addView(text("Perosak & kawalan",22,INK,true));CheckBox none=new CheckBox(this);none.setText("Tiada perosak dikesan");none.setTextSize(15);none.setChecked(draft.optBoolean("_noPest"));panel.addView(none);none.setOnCheckedChangeListener((b,checked)->{collect();put(draft,"_noPest",checked);redrawForm();});if(!none.isChecked()){for(int i=0;i<pests.length();i++){final int index=i;JSONObject pest=pests.optJSONObject(i);gap(panel,12);LinearLayout item=card(panel,BG);item.addView(text(pest.optString("name"),18,INK,true));item.addView(text(number(pest.optDouble("area"))+" ha  ·  Tahap "+pest.optInt("severity"),14,MUTED,false));addButton(item,"Buang perosak",false,()->{pests.remove(index);collect();redrawForm();});}addButton(panel,"+ Tambah perosak",false,this::addPest);}field(panel,"syor","Syor kawalan",false);fields.get("syor").setSingleLine(false);fields.get("syor").setMinLines(3);fields.get("syor").setLayoutParams(new LinearLayout.LayoutParams(-1,dp(112)));field(panel,"catatan","Catatan pemerhatian",false);fields.get("catatan").setSingleLine(false);fields.get("catatan").setMinLines(3);}
        if(step==3){panel.addView(text("Semak sebelum hantar",22,INK,true));String summary=draft.optString("namaTanaman")+"\n"+draft.optString("lokasi")+"\n"+draft.optString("daerah")+", "+draft.optString("negeri")+"\n"+draft.optString("tarikhBancian")+"\n\nLuas bertanam: "+draft.optString("luasBertanam")+" ha\n"+(draft.optBoolean("_noPest")?"Tiada perosak dikesan":pests.length()+" jenis perosak direkodkan");gap(panel,14);panel.addView(text(summary,16,INK,false));gap(panel,18);panel.addView(text("Gambar lapangan",18,INK,true));panel.addView(text(photos.length()+" gambar baharu · maksimum 4",14,MUTED,false));for(int i=0;i<photos.length();i++){final int index=i;photoThumbnail(panel,photos.optJSONObject(i));addButton(panel,photos.optJSONObject(i).optString("name")+"  ×",false,()->{photos.remove(index);collect();redrawForm();});}if(retainedImages.length()>0)panel.addView(text(retainedImages.length()+" gambar sedia ada dikekalkan",14,MUTED,false));if(editingId.isEmpty())addButton(panel,"Tambah gambar",false,this::photoMenu);else panel.addView(text("Gambar lama dikekalkan semasa pembetulan. Tambahan gambar untuk rekod lama masih melalui sistem web.",14,MUTED,false));field(panel,"captionGambar","Keterangan gambar",false);}
        LinearLayout actions=row();Button back=button("Kembali",false,()->{collect();step=Math.max(0,step-1);redrawForm();});back.setEnabled(step>0);actions.addView(back,new LinearLayout.LayoutParams(0,dp(52),1));Button next=button(step<3?"Seterusnya  →":"Hantar laporan",true,()->{collect();if(step<3){if(validateStep(step)){step++;saveDraft(false);redrawForm();}}else submit();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(52),1);lp.leftMargin=dp(10);actions.addView(next,lp);c.addView(actions);addButton(c,"Simpan draf di telefon",false,()->{collect();saveDraft(true);});c.addView(text("Draf telefon belum dihantar ke pelayan.",12,MUTED,false));}
    void collect(){for(Map.Entry<String,EditText> entry:fields.entrySet())put(draft,entry.getKey(),entry.getValue().getText().toString().trim());put(draft,"_pests",pests);put(draft,"_photos",photos);put(draft,"_editingId",editingId);put(draft,"_retained",retainedImages);put(draft,"_step",step);}
    boolean saveDraft(boolean notify){if(uid.isEmpty())return false;try{store.put("draft_"+uid,draft.toString());if(notify)toast("Draf disimpan pada telefon.");return true;}catch(Exception e){toast("Draf gagal disimpan. Semak ruang telefon; salinan asal dikekalkan.");return false;}}
    boolean validateStep(int current){String[] required=current==0?new String[]{"namaPegawai","email","tarikhBancian","negeri","daerah","lokasi","koordinat"}:current==1?new String[]{"kategori","namaTanaman","luasBertanam"}:new String[]{};for(String key:required)if(draft.optString(key).trim().isEmpty()){if(fields.containsKey(key))fields.get(key).setError("Maklumat diperlukan");toast("Lengkapkan semua maklumat bertanda *.");return false;}if(current==0){if(!android.util.Patterns.EMAIL_ADDRESS.matcher(draft.optString("email")).matches()){toast("E-mel tidak sah.");return false;}try{String[] coord=draft.optString("koordinat").split(",");double lat=Double.parseDouble(coord[0].trim()),lon=Double.parseDouble(coord[1].trim());if(coord.length!=2||!Double.isFinite(lat)||!Double.isFinite(lon)||Math.abs(lat)>90||Math.abs(lon)>180)throw new Exception();}catch(Exception e){toast("Koordinat mesti latitud, longitud yang sah.");return false;}}
        if(current==1&&(!(draft.optDouble("luasBertanam",0)>0)||!Double.isFinite(draft.optDouble("luasBertanam",0)))){toast("Luas bertanam mesti melebihi sifar.");return false;}if(current==2&&!draft.optBoolean("_noPest")&&pests.length()==0){toast("Tambah perosak atau tandakan tiada perosak dikesan.");return false;}if(current==2&&!draft.optBoolean("_noPest")){for(int i=0;i<pests.length();i++)if(pests.optJSONObject(i).optDouble("area")>draft.optDouble("luasBertanam")){toast("Luas serangan perosak melebihi luas bertanam.");return false;}}return true;}
    void addPest(){collect();LinearLayout c=column();c.setPadding(dp(22),dp(12),dp(22),dp(12));AutoCompleteTextView name=new AutoCompleteTextView(this);name.setTextSize(16);name.setHint("Nama perosak");List<String> options=strings(array(object(master,draft.optString("kategori")),draft.optString("namaTanaman")));name.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_dropdown_item_1line,options));name.setThreshold(1);c.addView(name,new LinearLayout.LayoutParams(-1,dp(55)));EditText area=input(c,"Luas serangan (ha)","",true);Spinner severity=new Spinner(this);severity.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"T1 · Sangat rendah","T2 · Rendah","T3 · Sederhana","T4 · Teruk","T5 · Sangat teruk"}));gap(c,14);c.addView(severity);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Tambah perosak").setView(c).setPositiveButton("Tambah",null).setNegativeButton("Batal",null).create();dialog.setOnShowListener(v->dialog.getButton(-1).setOnClickListener(w->{String n=name.getText().toString().trim();double a;try{a=Double.parseDouble(area.getText().toString());}catch(Exception e){a=-1;}if(n.isEmpty()||!Double.isFinite(a)||a<0||a>draft.optDouble("luasBertanam",0)){toast("Isi nama dan luas serangan yang sah.");return;}for(int i=0;i<pests.length();i++)if(pests.optJSONObject(i).optString("name").equalsIgnoreCase(n)){toast("Perosak ini sudah ditambah.");return;}pests.put(obj("name",n,"area",a,"severity",severity.getSelectedItemPosition()+1));dialog.dismiss();redrawForm();}));dialog.show();}
    void submit(){if(posting)return;for(int i=0;i<3;i++)if(!validateStep(i)){step=i;redrawForm();return;}new AlertDialog.Builder(this).setTitle("Hantar untuk pengesahan?").setMessage("Semak lokasi, tanaman dan maklumat serangan. Laporan akan dihantar ke sistem v2.").setPositiveButton("Hantar",(d,w)->{posting=true;if(!saveDraft(false)){posting=false;return;}JSONObject payload=new JSONObject();for(String key:new String[]{"namaPegawai","email","tarikhBancian","negeri","daerah","lokasi","koordinat","kategori","namaTanaman","varieti","umurTanaman","luasBertanam","syor","catatan","captionGambar"})put(payload,key,draft.optString(key));JSONObject areas=new JSONObject(),percents=new JSONObject(),severity=new JSONObject();List<String> names=new ArrayList<>();if(!draft.optBoolean("_noPest"))for(int i=0;i<pests.length();i++){JSONObject p=pests.optJSONObject(i);String n=p.optString("name");names.add(n);put(areas,n,p.optDouble("area"));put(percents,n,100*p.optDouble("area")/draft.optDouble("luasBertanam"));put(severity,n,p.optInt("severity"));}put(payload,"luasSerangan",areas);put(payload,"peratusSerangan",percents);put(payload,"keterukan",severity);put(payload,"senaraiPerosak",String.join(", ",names));put(payload,"statusRekod","BARU");put(payload,"images",photos.toString());if(!editingId.isEmpty()){put(payload,"row",editingId);put(payload,"retainedImages",retainedImages);put(payload,"newImageLinks",new JSONArray());}if(editingId.isEmpty()){put(payload,"submissionId",java.util.UUID.randomUUID().toString());put(draft,"_pendingPayload",payload);if(!saveDraft(false)){draft.remove("_pendingPayload");posting=false;return;}posting=false;redrawForm();sendPending();}else request("data/update-entry",payload,r->submissionDone());}).setNegativeButton("Semak semula",null).show();}
    void pendingScreen(){heading("PENGHANTARAN LAPORAN","Menunggu pengesahan","Salinan asal disimpan pada telefon");LinearLayout c=scroller();LinearLayout panel=card(c,WHITE);panel.addView(text(draft.optString("namaTanaman"),22,INK,true));gap(panel,8);panel.addView(text(draft.optString("lokasi")+" · "+draft.optString("tarikhBancian"),15,MUTED,false));gap(panel,20);panel.addView(text("Internet mungkin terputus sebelum pengesahan diterima. Tekan semak & hantar semula; sistem menggunakan ID yang sama untuk mengelakkan laporan berganda.",16,INK,false));gap(panel,12);panel.addView(text("Borang dikunci sementara supaya kandungan penghantaran tidak berubah. Anda boleh keluar aplikasi dan sambung kemudian.",14,MUTED,false));addButton(c,"Semak & hantar semula",true,this::sendPending);}
    void sendPending(){if(posting)return;JSONObject payload=object(draft,"_pendingPayload");if(!payload.has("submissionId"))return;posting=true;request("data/submission-status",obj("submissionId",payload.optString("submissionId")),status->{if(status.optInt("protocol")!=1){posting=false;alert("Pelayan belum sedia","Pentadbir perlu mengaktifkan penghantaran selamat. Draf dikekalkan.");return;}if(status.optBoolean("received")){submissionDone();return;}request("data/submit-bancian",payload,r->submissionDone());});}
    void submissionDone(){posting=false;fields.clear();store.remove("draft_"+uid);draft=new JSONObject();pests=new JSONArray();photos=new JSONArray();editingId="";retainedImages=new JSONArray();step=0;toast("Laporan berjaya diterima untuk pengesahan.");show("tasks");}
    void editRecord(JSONObject r){initDraft();if(draft.has("_pendingPayload")){alert("Penghantaran belum disahkan","Selesaikan penghantaran dalam Borang dahulu. Draf dikunci supaya salinan asal tidak hilang.");return;}if(!store.get("draft_"+uid).isEmpty()){new AlertDialog.Builder(this).setTitle("Gantikan draf di telefon?").setMessage("Satu draf sudah disimpan untuk akaun ini. Membuka pembetulan akan menggantikannya. Sambung atau hantar draf sedia ada jika masih diperlukan.").setNegativeButton("Kekalkan draf",null).setPositiveButton("Gantikan",(d,w)->replaceDraftFromRecord(r)).show();}else replaceDraftFromRecord(r);}
    void replaceDraftFromRecord(JSONObject r){fields.clear();draft=obj("namaPegawai",r.optString("pg"),"email",r.optString("em"),"tarikhBancian",r.optString("t").split("T")[0],"negeri",r.optString("n"),"daerah",r.optString("d"),"lokasi",r.optString("l"),"koordinat",r.optString("c"),"kategori",r.optString("kt"),"namaTanaman",r.optString("tn"),"varieti",r.optString("vr"),"umurTanaman",r.optString("um"),"luasBertanam",r.optDouble("lt"),"syor",r.optString("s"),"catatan",r.optString("catatan"),"captionGambar",r.optString("caption"));editingId=r.optString("id");photos=new JSONArray();pests=new JSONArray();retainedImages=new JSONArray();for(String link:r.optString("im").split(","))if(link.trim().startsWith("https://"))retainedImages.put(link.trim());JSONObject area=object(r,"p"),sev=object(r,"pk");Iterator<String> keys=area.keys();while(keys.hasNext()){String n=keys.next();pests.put(obj("name",n,"area",area.optDouble(n),"severity",Math.max(1,Math.min(5,sev.optInt(n,1)))));}put(draft,"_noPest",pests.length()==0);collect();saveDraft(false);step=0;show("form");}
    void getLocation(){if(checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},31);return;}LocationManager manager=(LocationManager)getSystemService(LOCATION_SERVICE);stopLocation();try{boolean precise=checkSelfPermission(Manifest.permission.ACCESS_FINE_LOCATION)==PackageManager.PERMISSION_GRANTED;String provider=precise&&manager.isProviderEnabled(LocationManager.GPS_PROVIDER)?LocationManager.GPS_PROVIDER:LocationManager.NETWORK_PROVIDER;if(!manager.isProviderEnabled(provider))throw new IllegalStateException();locationListener=new LocationListener(){public void onLocationChanged(Location l){if(!l.hasAccuracy()||SystemClock.elapsedRealtimeNanos()-l.getElapsedRealtimeNanos()>120000000000L)return;stopLocation();if(screen.equals("form")&&fields.containsKey("koordinat")){fields.get("koordinat").setText(String.format(Locale.US,"%.6f, %.6f",l.getLatitude(),l.getLongitude()));put(draft,"koordinat",fields.get("koordinat").getText().toString());put(draft,"_gpsAccuracy",l.getAccuracy());toast("Ketepatan lokasi: ±"+Math.round(l.getAccuracy())+" meter. Semak sebelum hantar.");}}public void onStatusChanged(String p,int s,Bundle b){}public void onProviderEnabled(String p){}public void onProviderDisabled(String p){}};manager.requestLocationUpdates(provider,1000,0,locationListener,Looper.getMainLooper());toast("Mendapatkan lokasi…");locationTimeout=()->{if(locationListener!=null){stopLocation();toast("Lokasi belum diperoleh. Cuba di kawasan terbuka atau isi koordinat manual.");}};handler.postDelayed(locationTimeout,20000);}catch(Exception e){stopLocation();toast("Hidupkan lokasi telefon atau isi koordinat manual.");}}
    void stopLocation(){if(locationTimeout!=null){handler.removeCallbacks(locationTimeout);locationTimeout=null;}if(locationListener!=null){try{((LocationManager)getSystemService(LOCATION_SERVICE)).removeUpdates(locationListener);}catch(Exception ignored){}locationListener=null;}}
    void photoMenu(){collect();if(photos.length()>=4){toast("Maksimum 4 gambar.");return;}new AlertDialog.Builder(this).setTitle("Gambar lapangan").setItems(new String[]{"Ambil gambar","Pilih gambar"},(d,n)->{if(n==0)camera();else{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");startActivityForResult(i,41);}}).show();}
    void camera(){try{ContentValues values=new ContentValues();values.put(MediaStore.Images.Media.DISPLAY_NAME,"PNR-"+System.currentTimeMillis()+".jpg");values.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");values.put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/PNR");values.put(MediaStore.Images.Media.IS_PENDING,1);cameraUri=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,values);if(cameraUri==null)throw new IOException();Intent intent=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);intent.putExtra(MediaStore.EXTRA_OUTPUT,cameraUri);intent.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_READ_URI_PERMISSION);intent.setClipData(ClipData.newRawUri("Gambar PNR",cameraUri));startActivityForResult(intent,42);}catch(Exception e){toast("Kamera tidak tersedia. Pilih gambar dari telefon.");clearPhoto();}}
    void clearPhoto(){if(cameraUri!=null){try{getContentResolver().delete(cameraUri,null,null);}catch(Exception ignored){}cameraUri=null;}}
    void processPhoto(Uri uri){final String owner=uid;final JSONObject target=draft;photoProcessing=true;busy(true);executor.execute(()->{try{Bitmap small=ImageDecoder.decodeBitmap(ImageDecoder.createSource(getContentResolver(),uri),(decoder,info,source)->{int width=info.getSize().getWidth(),height=info.getSize().getHeight();float scale=Math.min(1f,1024f/Math.max(width,height));decoder.setTargetSize(Math.max(1,(int)(width*scale)),Math.max(1,(int)(height*scale)));decoder.setAllocator(ImageDecoder.ALLOCATOR_SOFTWARE);});ByteArrayOutputStream bytes=new ByteArrayOutputStream();small.compress(Bitmap.CompressFormat.JPEG,72,bytes);small.recycle();if(bytes.size()>500000)throw new IOException();String data="data:image/jpeg;base64,"+android.util.Base64.encodeToString(bytes.toByteArray(),android.util.Base64.NO_WRAP);handler.post(()->{photoProcessing=false;busy(false);if(isDestroyed()||!uid.equals(owner)||draft!=target)return;if(photos.length()>=4){toast("Maksimum 4 gambar.");return;}photos.put(obj("name","PNR-"+System.currentTimeMillis()+".jpg","dataUrl",data));collect();saveDraft(false);if(screen.equals("form"))redrawForm();});}catch(Exception e){handler.post(()->{photoProcessing=false;busy(false);toast("Gambar tidak dapat diproses. Pilih JPEG/PNG lebih kecil.");});}});}
    void profile(){heading("AKAUN & MODUL","Ruang kerja anda",user.optString("role")+" · "+user.optString("state"));LinearLayout c=scroller();LinearLayout card=card(c,INK);card.addView(text(user.optString("name"),24,WHITE,true));gap(card,8);card.addView(text(uid,14,LIME,false));addButton(c,"Sasaran KPI",false,this::kpi);if(user.optString("role").equalsIgnoreCase("ADMIN"))addButton(c,"Senarai pengguna",false,this::users);section(c,"Pemantauan & pentadbiran","Modul mengikut akses akaun");module(c,"RPW","Perangkap RPW","Buka ruang pemantauan native",BLUE,()->navigate("rpw"));addButton(c,"Sistem web penuh — pelayar",false,()->external(ApiClient.ORIGIN+"/"));gap(c,15);c.addView(text("PNR Native 2.2\nAplikasi pelaporan lapangan",14,MUTED,false));gap(c,8);c.addView(text("Draf telefon disimpan secara setempat. Penghantaran dan pengesahan memerlukan internet.",14,MUTED,false));addButton(c,"Log keluar",false,()->new AlertDialog.Builder(this).setMessage("Log keluar? Draf telefon akaun ini dikekalkan.").setPositiveButton("Log keluar",(d,w)->{store.remove("session");token="";uid="";records=new JSONArray();master=new JSONObject();draft=new JSONObject();pests=new JSONArray();photos=new JSONArray();hasLoaded=false;cacheTime="";editingId="";retainedImages=new JSONArray();step=0;rpw.clear();fields.clear();query="";stateFilter="";showLogin();}).setNegativeButton("Batal",null).show());}
    void kpi(){epoch++;shell(true);heading("SASARAN PEMANTAUAN","Sasaran KPI","Mengikut negeri dan tanaman");LinearLayout c=scroller();addButton(c,"Kembali ke akaun",false,()->show("profile"));request("data/kpi",obj(),r->{JSONObject targets=object(r,"dataSasaran");for(String state:keys(targets)){if(!user.optString("state").equals("ALL")&&!state.equalsIgnoreCase(user.optString("state")))continue;JSONObject crops=object(targets,state);LinearLayout card=card(c,WHITE);card.addView(text(state,20,INK,true));for(String crop:keys(crops)){gap(card,12);card.addView(text(crop,16,INK,false));card.addView(text(number(crops.optDouble(crop))+" ha sasaran",14,MUTED,false));}}});}
    void users(){epoch++;shell(true);heading("PENTADBIRAN","Pengguna","Senarai akaun berdaftar");LinearLayout c=scroller();addButton(c,"Kembali ke akaun",false,()->show("profile"));request("users/list",obj(),r->{JSONArray users=array(r,"users");for(int i=0;i<users.length();i++){JSONObject u=users.optJSONObject(i);LinearLayout card=card(c,WHITE);card.addView(text(u.optString("nama"),18,INK,true));card.addView(text(u.optString("role")+" · "+u.optString("negeri"),14,MUTED,false));card.addView(text(u.optString("status"),14,INK,true));}});}
    String csv(String s){if(s.matches("(?s)^\\s*[=+@\\t\\r-].*"))s="\'"+s;return "\""+s.replace("\"","\"\"")+"\"";}
    void exportCsv(){StringBuilder b=new StringBuilder("\uFEFFTarikh,Negeri,Daerah,Lokasi,Tanaman,Luas bertanam ha,Luas serangan ha\r\n");for(JSONObject r:filtered()){b.append(csv(r.optString("t"))).append(',').append(csv(r.optString("n"))).append(',').append(csv(r.optString("d"))).append(',').append(csv(r.optString("l"))).append(',').append(csv(r.optString("tn"))).append(',').append(r.optDouble("lt",0)).append(',').append(r.optDouble("ls",0)).append("\r\n");}saveExport(b.toString(),"PNR-Rekod-"+date()+".csv");}
    void exportPdf(){try{saveBinary(ReportPdf.create(filtered(),user.optString("name"),date()),"PNR-Rekod-"+date()+".pdf","application/pdf");}catch(Exception e){alert("PDF belum berjaya","Kecilkan tapisan rekod dan cuba semula.");}}
    void saveExport(String csv,String name){saveBinary(csv.getBytes(java.nio.charset.StandardCharsets.UTF_8),name,"text/csv");}
    void saveBinary(byte[] bytes,String name,String mime){try{store.put("export_"+uid,"B64:"+android.util.Base64.encodeToString(bytes,android.util.Base64.NO_WRAP));exportBytes=bytes;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType(mime);i.putExtra(Intent.EXTRA_TITLE,name);startActivityForResult(i,43);}catch(Exception e){store.remove("export_"+uid);exportBytes=null;alert("Eksport belum berjaya","Pemilih fail tidak tersedia atau storan penuh.");}}

    void photoThumbnail(LinearLayout c,JSONObject photo){try{String data=photo.optString("dataUrl");byte[] bytes=android.util.Base64.decode(data.substring(data.indexOf(',')+1),android.util.Base64.DEFAULT);BitmapFactory.Options options=new BitmapFactory.Options();options.inSampleSize=4;Bitmap bitmap=BitmapFactory.decodeByteArray(bytes,0,bytes.length,options);ImageView view=new ImageView(this);view.setImageBitmap(bitmap);view.setScaleType(ImageView.ScaleType.CENTER_CROP);view.setContentDescription("Pratonton "+photo.optString("name"));c.addView(view,new LinearLayout.LayoutParams(-1,dp(160)));}catch(Exception ignored){}}
    void external(String url){Uri uri=Uri.parse(url);if(!Arrays.asList("https","geo").contains(uri.getScheme()))return;try{startActivity(new Intent(Intent.ACTION_VIEW,uri));}catch(Exception e){toast("Tiada aplikasi untuk membuka pautan.");}}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==41&&result==RESULT_OK&&data!=null&&data.getData()!=null)processPhoto(data.getData());if(request==42){if(result==RESULT_OK&&cameraUri!=null){Uri uri=cameraUri;try{ContentValues done=new ContentValues();done.put(MediaStore.Images.Media.IS_PENDING,0);getContentResolver().update(uri,done,null,null);}catch(Exception ignored){}cameraUri=null;processPhoto(uri);}else clearPhoto();}if(request==43){byte[] bytes=exportBytes;exportBytes=null;store.remove("export_"+uid);if(result==RESULT_OK&&data!=null&&data.getData()!=null&&bytes!=null){Uri destination=data.getData();executor.execute(()->{try(OutputStream out=getContentResolver().openOutputStream(destination)){if(out==null)throw new IOException();out.write(bytes);handler.post(()->toast("Fail eksport berjaya disimpan."));}catch(Exception e){handler.post(()->toast("Fail gagal disimpan."));}});}}}
    @Override public void onRequestPermissionsResult(int request,String[] permissions,int[] result){super.onRequestPermissionsResult(request,permissions,result);if(request==31){if(checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)==PackageManager.PERMISSION_GRANTED)getLocation();else new AlertDialog.Builder(this).setTitle("Akses lokasi tidak dibenarkan").setMessage("Anda boleh isi koordinat manual atau benarkan lokasi dalam Tetapan aplikasi.").setPositiveButton("Tetapan",(d,w)->startActivity(new Intent(android.provider.Settings.ACTION_APPLICATION_DETAILS_SETTINGS,Uri.parse("package:"+getPackageName())))).setNegativeButton("Isi manual",null).show();}}
    @Override public void onBackPressed(){if(posting||photoProcessing){toast("Tunggu proses selesai dahulu.");return;}if(screen.equals("form")&&step>0){collect();step--;redrawForm();}else if(!screen.equals("home")&&!screen.equals("login"))navigate("home");else new AlertDialog.Builder(this).setMessage("Tutup aplikasi?").setPositiveButton("Tutup",(d,w)->finish()).setNegativeButton("Batal",null).show();}
    @Override protected void onSaveInstanceState(Bundle out){if(screen.equals("form")){collect();saveDraft(false);}out.putString("screen",screen);out.putInt("step",step);out.putString("query",query);out.putString("period",period);out.putString("stateFilter",stateFilter);out.putString("analysisTab",dashboard.tab);out.putString("district",dashboard.district);out.putString("crop",dashboard.crop);out.putString("pest",dashboard.pest);out.putString("searchField",explorer.searchField);out.putString("recordSort",explorer.sort);out.putBoolean("recordTable",explorer.table);out.putBoolean("exportPending",exportBytes!=null);if(cameraUri!=null)out.putString("cameraUri",cameraUri.toString());super.onSaveInstanceState(out);}
    @Override protected void onPause(){if(screen.equals("form")){collect();saveDraft(false);}stopLocation();super.onPause();}
    @Override protected void onDestroy(){epoch++;handler.removeCallbacksAndMessages(null);stopLocation();executor.shutdownNow();super.onDestroy();}
    byte[] read(InputStream in)throws IOException{ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)out.write(b,0,n);return out.toByteArray();}
}
