package my.pnr.digital.v2;

import android.Manifest;
import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.*;
import android.graphics.drawable.GradientDrawable;
import android.location.*;
import android.net.Uri;
import android.os.*;
import android.provider.MediaStore;
import android.text.*;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.*;
import java.util.concurrent.*;

/** Native Android screens. This activity does not embed web content. */
public class MainActivity extends Activity {
    final int INK=Color.rgb(23,47,37), MUTED=Color.rgb(107,122,111), BG=Color.rgb(245,247,243), LIME=Color.rgb(216,239,151), WHITE=Color.WHITE, LINE=Color.rgb(225,232,220), RED=Color.rgb(166,64,51);
    final ExecutorService executor=Executors.newSingleThreadExecutor();
    final Handler handler=new Handler(Looper.getMainLooper());
    NativeStore store;JSONObject user=new JSONObject(),master=new JSONObject(),districts=new JSONObject(),draft=new JSONObject();
    JSONArray records=new JSONArray(),pests=new JSONArray(),photos=new JSONArray();
    String token="",uid="",query="",period="all",stateFilter="",screen="home",editingId="";JSONArray retainedImages=new JSONArray();
    int epoch=0,step=0,page=0;boolean posting=false,hasLoaded=false;LinearLayout root,body,nav,header;FrameLayout content;TextView status;ProgressBar loading;
    final Map<String,EditText> fields=new LinkedHashMap<>();
    Uri cameraUri;LocationListener locationListener; byte[] exportBytes;
    interface Success {void accept(JSONObject data);}
    int dp(float n){return (int)(n*getResources().getDisplayMetrics().density+.5f);}
    JSONObject obj(Object... pairs){JSONObject o=new JSONObject();for(int i=0;i<pairs.length;i+=2)put(o,pairs[i].toString(),pairs[i+1]);return o;}
    void put(JSONObject o,String key,Object value){try{o.put(key,value);}catch(JSONException ignored){}}
    JSONObject object(JSONObject o,String key){Object x=o.opt(key);if(x instanceof JSONObject)return (JSONObject)x;try{return new JSONObject(String.valueOf(x));}catch(Exception e){return new JSONObject();}}
    JSONArray array(JSONObject o,String key){JSONArray a=o.optJSONArray(key);return a==null?new JSONArray():a;}
    String date(){return new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date());}
    String number(double x){return String.format(Locale.US,"%,.2f",x);}
    GradientDrawable shape(int color,int radius){GradientDrawable d=new GradientDrawable();d.setColor(color);d.setCornerRadius(dp(radius));return d;}
    TextView text(String value,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(value);t.setTextSize(size);t.setTextColor(color);t.setFontFeatureSettings("tnum");t.setTypeface(android.graphics.Typeface.create(bold?"sans-serif-medium":"sans-serif",0));t.setLineSpacing(dp(3),1);return t;}
    LinearLayout column(){LinearLayout c=new LinearLayout(this);c.setOrientation(1);return c;}
    LinearLayout row(){LinearLayout r=new LinearLayout(this);r.setGravity(Gravity.CENTER_VERTICAL);return r;}
    void gap(LinearLayout c,int height){Space s=new Space(this);c.addView(s,new LinearLayout.LayoutParams(1,dp(height)));}
    Button button(String label,boolean primary,Runnable action){Button b=new Button(this);b.setText(label);b.setTextSize(14);b.setAllCaps(false);b.setTextColor(primary?WHITE:INK);b.setBackground(shape(primary?INK:LINE,14));b.setMinHeight(dp(48));b.setPadding(dp(16),dp(8),dp(16),dp(8));b.setOnClickListener(v->action.run());return b;}
    void addButton(LinearLayout c,String label,boolean primary,Runnable action){Button b=button(label,primary,action);LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,dp(50));lp.topMargin=dp(10);c.addView(b,lp);}
    LinearLayout card(LinearLayout parent,int color){LinearLayout c=column();c.setPadding(dp(20),dp(20),dp(20),dp(20));c.setBackground(shape(color,22));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.bottomMargin=dp(14);parent.addView(c,lp);return c;}
    void toast(String message){Toast.makeText(this,message,Toast.LENGTH_LONG).show();}
    void alert(String title,String message){new AlertDialog.Builder(this).setTitle(title).setMessage(message).setPositiveButton("OK",null).show();}
    void busy(boolean value){loading.setVisibility(value?View.VISIBLE:View.GONE);}
    void request(String route,JSONObject payload,Success success){
        final int generation=epoch;final String auth=token,account=uid;busy(true);
        executor.execute(()->{try{JSONObject result=ApiClient.post(route,payload,auth,account);handler.post(()->{if(isFinishing()||generation!=epoch)return;busy(false);success.accept(result);});}catch(Exception e){handler.post(()->{if(isFinishing()||generation!=epoch)return;busy(false);posting=false;if(e instanceof ApiClient.ApiError&&((ApiClient.ApiError)e).status==401&&!route.equals("auth/login")){store.remove("session");token="";showLogin();toast("Sesi tamat. Log masuk semula.");}else alert("Belum berjaya",e instanceof ApiClient.ApiError?e.getMessage():"Semak sambungan internet dan cuba lagi. Jika sedang menghantar laporan, semak Tugasan sebelum menghantar semula.");});}});
    }
    @Override public void onCreate(Bundle saved){super.onCreate(saved);getWindow().setStatusBarColor(BG);getWindow().setNavigationBarColor(WHITE);getWindow().getDecorView().setSystemUiVisibility(View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR|View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR);store=new NativeStore(this);try(InputStream in=getAssets().open("districts.json")){districts=new JSONObject(new String(read(in),"UTF-8"));}catch(Exception ignored){}
        try{JSONObject session=new JSONObject(store.get("session"));user=session.getJSONObject("user");uid=session.getString("uid");token=user.optString("token");}catch(Exception ignored){}
        root=column();root.setBackgroundColor(BG);if(Build.VERSION.SDK_INT>=30)root.setOnApplyWindowInsetsListener((view,insets)->{Insets bars=insets.getInsets(WindowInsets.Type.systemBars()|WindowInsets.Type.ime());view.setPadding(bars.left,bars.top,bars.right,bars.bottom);return insets;});setContentView(root);
        if(token.isEmpty())showLogin();else{show("home");loadData();loadMaster();}
    }
    void shell(boolean logged){root.removeAllViews();header=column();header.setPadding(dp(24),dp(18),dp(24),dp(14));root.addView(header);loading=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);loading.setIndeterminate(true);loading.setVisibility(View.GONE);root.addView(loading,new LinearLayout.LayoutParams(-1,dp(3)));content=new FrameLayout(this);root.addView(content,new LinearLayout.LayoutParams(-1,0,1));if(logged){nav=row();nav.setPadding(dp(8),dp(8),dp(8),dp(8));nav.setBackgroundColor(WHITE);root.addView(nav);String[] names={"Utama","Rekod","Bancian","Tugasan","Akaun"},keys={"home","records","form","tasks","profile"};int[] icons={android.R.drawable.ic_menu_view,android.R.drawable.ic_menu_agenda,android.R.drawable.ic_input_add,android.R.drawable.ic_menu_edit,android.R.drawable.ic_menu_myplaces};for(int i=0;i<names.length;i++){final String dest=keys[i];LinearLayout item=column();item.setGravity(Gravity.CENTER);item.setPadding(dp(2),dp(8),dp(2),dp(8));item.setBackground(shape(screen.equals(dest)?LIME:WHITE,16));ImageView icon=new ImageView(this);icon.setImageResource(icons[i]);icon.setColorFilter(INK);item.addView(icon,new LinearLayout.LayoutParams(dp(23),dp(23)));TextView label=text(names[i],12,INK,screen.equals(dest));label.setGravity(Gravity.CENTER);item.addView(label);item.setContentDescription(names[i]);item.setFocusable(true);item.setOnClickListener(v->navigate(dest));nav.addView(item,new LinearLayout.LayoutParams(0,dp(62),1));}}}
    LinearLayout scroller(){ScrollView scroll=new ScrollView(this);scroll.setFillViewport(true);scroll.setClipToPadding(false);body=column();body.setPadding(dp(22),dp(12),dp(22),dp(24));scroll.addView(body);content.addView(scroll,new FrameLayout.LayoutParams(-1,-1));return body;}
    void heading(String eyebrow,String title,String subtitle){header.addView(text(eyebrow.toUpperCase(Locale.ROOT),12,MUTED,true));gap(header,6);header.addView(text(title,28,INK,true));if(!subtitle.isEmpty()){gap(header,4);header.addView(text(subtitle,14,MUTED,false));}}
    void showLogin(){epoch++;screen="login";shell(false);header.setPadding(dp(28),dp(24),dp(28),dp(12));heading("PNR DIGITAL • ANDROID","Bancian lebih mudah.","Biosekuriti tumbuhan · Jabatan Pertanian");LinearLayout c=scroller();LinearLayout hero=card(c,INK);hero.addView(text("Data lapangan.\nTindakan bermakna.",30,LIME,true));gap(hero,12);hero.addView(text("Aplikasi pemantauan perosak tanaman",15,WHITE,false));gap(c,12);c.addView(text("Selamat kembali",24,INK,true));gap(c,6);c.addView(text("Gunakan akaun sistem PNR v2 anda.",14,MUTED,false));EditText id=input(c,"ID pengguna","",false);id.setAutofillHints(View.AUTOFILL_HINT_USERNAME);EditText pass=input(c,"Kata laluan","",false);pass.setInputType(129);pass.setAutofillHints(View.AUTOFILL_HINT_PASSWORD);addButton(c,"Log masuk",true,()->{String u=id.getText().toString().trim(),p=pass.getText().toString();if(u.isEmpty()||p.isEmpty()){toast("Isi ID dan kata laluan.");return;}request("auth/login",obj("u",u,"p",p),result->{uid=u;user=result;token=result.optString("token");try{store.put("session",obj("uid",uid,"user",user).toString());}catch(Exception e){toast("Sesi tidak dapat disimpan. Log masuk diperlukan apabila aplikasi dibuka semula.");}show("home");loadData();loadMaster();});});addButton(c,"Daftar / bantuan akaun",false,()->external(ApiClient.ORIGIN+"/"));}
    EditText input(LinearLayout c,String label,String value,boolean numeric){gap(c,12);c.addView(text(label,14,INK,true));gap(c,6);EditText e=new EditText(this);e.setText(value);e.setTextSize(16);e.setTextColor(INK);e.setHint(label);e.setSingleLine(true);e.setPadding(dp(14),dp(10),dp(14),dp(10));GradientDrawable bg=shape(WHITE,12);bg.setStroke(dp(1),LINE);e.setBackground(bg);if(numeric)e.setInputType(8194);c.addView(e,new LinearLayout.LayoutParams(-1,dp(52)));return e;}
    void navigate(String destination){if(posting){toast("Tunggu penghantaran selesai dahulu.");return;}if(screen.equals("form")&&!destination.equals("form")){collect();saveDraft(false);}show(destination);}
    void show(String target){epoch++;screen=target;shell(true);if(target.equals("home"))home();else if(target.equals("records"))recordScreen();else if(target.equals("form"))form();else if(target.equals("tasks"))tasks(false);else profile();}
    void loadData(){request("data/analytics",obj("state",user.optString("state","ALL")),result->{records=array(result,"records");hasLoaded=true;if(screen.equals("home"))show("home");else if(screen.equals("records"))show("records");});}
    void loadMaster(){final String auth=token,account=uid;executor.execute(()->{try{JSONObject result=ApiClient.post("data/master-tanaman",obj(),auth,account);handler.post(()->{master=object(result,"data");});}catch(Exception ignored){}});}
    List<JSONObject> filtered(){List<JSONObject> result=new ArrayList<>();String now=date();for(int i=0;i<records.length();i++){JSONObject r=records.optJSONObject(i);if(r==null)continue;String t=r.optString("t");if(period.equals("month")&&!t.startsWith(now.substring(0,7)))continue;if(period.equals("year")&&!t.startsWith(now.substring(0,4)))continue;if(!stateFilter.isEmpty()&&!stateFilter.equals(r.optString("n")))continue;if(!query.isEmpty()&&!r.toString().toLowerCase(Locale.ROOT).contains(query.toLowerCase(Locale.ROOT)))continue;result.add(r);}return result;}
    void filters(LinearLayout c){LinearLayout line=row();String[] values={"all","month","year"},labels={"Semua","Bulan ini","Tahun ini"};for(int i=0;i<values.length;i++){final String val=values[i];Button b=button(labels[i],period.equals(val),()->{period=val;page=0;show(screen);});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(43),1);lp.rightMargin=dp(5);line.addView(b,lp);}c.addView(line);gap(c,12);if(user.optString("state").equals("ALL")){Button state=button(stateFilter.isEmpty()?"Semua negeri  ▾":stateFilter+"  ▾",false,()->{TreeSet<String> names=new TreeSet<>();for(int i=0;i<records.length();i++)names.add(records.optJSONObject(i).optString("n"));List<String> all=new ArrayList<>();all.add("Semua negeri");all.addAll(names);new AlertDialog.Builder(this).setTitle("Negeri").setItems(all.toArray(new String[0]),(d,n)->{stateFilter=n==0?"":all.get(n);show(screen);}).show();});c.addView(state);gap(c,12);}}
    void home(){heading("PNR DIGITAL  /  V2","Ringkasan bancian","Hai, "+user.optString("name","Pegawai"));LinearLayout c=scroller();filters(c);List<JSONObject> data=filtered();double area=0,attack=0;TreeMap<String,Double> top=new TreeMap<>();for(JSONObject r:data){area+=r.optDouble("lt",0);attack+=r.optDouble("ls",0);JSONObject p=object(r,"p");Iterator<String> keys=p.keys();while(keys.hasNext()){String key=keys.next();top.put(key,top.getOrDefault(key,0d)+p.optDouble(key,0));}}
        LinearLayout hero=card(c,INK);hero.addView(text("REKOD DISAHKAN",12,LIME,true));gap(hero,8);hero.addView(text(hasLoaded?Integer.toString(data.size()):"—",44,WHITE,true));hero.addView(text(hasLoaded?"Dalam tempoh dan negeri dipilih":"Muatkan data untuk melihat ringkasan",14,Color.rgb(190,209,183),false));addButton(hero,"+  Bancian baharu",false,()->navigate("form"));
        LinearLayout metrics=row();metrics.setGravity(Gravity.TOP);for(int i=0;i<2;i++){LinearLayout cell=column();cell.setPadding(dp(16),dp(18),dp(12),dp(18));cell.setBackground(shape(WHITE,18));cell.addView(text(i==0?"Luas bertanam":"Luas serangan",14,MUTED,false));gap(cell,8);cell.addView(text(hasLoaded?number(i==0?area:attack):"—",23,INK,true));cell.addView(text("hektar dilaporkan",12,MUTED,false));LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,-2,1);lp.rightMargin=dp(i==0?10:0);metrics.addView(cell,lp);}c.addView(metrics);gap(c,10);c.addView(text("Luas boleh bertindih antara lawatan atau perosak.",12,MUTED,false));gap(c,22);
        LinearLayout pestCard=card(c,WHITE);pestCard.addView(text("Perosak utama",20,INK,true));gap(pestCard,6);pestCard.addView(text("Mengikut luas serangan · ha",12,MUTED,false));List<Map.Entry<String,Double>> ranked=new ArrayList<>(top.entrySet());ranked.sort((a,b)->Double.compare(b.getValue(),a.getValue()));if(ranked.isEmpty()){gap(pestCard,18);pestCard.addView(text(hasLoaded?"Tiada serangan dalam pilihan ini.":"Data belum dimuatkan.",14,MUTED,false));}for(int i=0;i<Math.min(5,ranked.size());i++){Map.Entry<String,Double> r=ranked.get(i);gap(pestCard,16);LinearLayout line=row();line.addView(text(r.getKey(),14,INK,true),new LinearLayout.LayoutParams(0,-2,1));line.addView(text(number(r.getValue()),14,MUTED,false));pestCard.addView(line);ProgressBar meter=new ProgressBar(this,null,android.R.attr.progressBarStyleHorizontal);meter.setMax(1000);meter.setProgress((int)(1000*r.getValue()/Math.max(1,ranked.get(0).getValue())));meter.setProgressTintList(android.content.res.ColorStateList.valueOf(INK));pestCard.addView(meter,new LinearLayout.LayoutParams(-1,dp(10)));}
        addButton(c,hasLoaded?"Kemas kini data":"Muatkan data",false,this::loadData);}
    void recordScreen(){heading("DAFTAR BANCIAN","Rekod lapangan",records.length()+" rekod tersedia");LinearLayout c=scroller();filters(c);EditText search=input(c,"Cari lokasi, tanaman atau perosak",query,false);gap(c,14);LinearLayout list=column();c.addView(list);renderRecords(list);search.addTextChangedListener(new TextWatcher(){Runnable work;public void beforeTextChanged(CharSequence s,int a,int count,int after){}public void onTextChanged(CharSequence s,int start,int before,int count){query=s.toString();page=0;if(work!=null)handler.removeCallbacks(work);work=()->renderRecords(list);handler.postDelayed(work,200);}public void afterTextChanged(Editable e){}});addButton(c,"Eksport CSV rekod ditapis",false,this::exportCsv);addButton(c,"Muat semula rekod",false,this::loadData);}
    void renderRecords(LinearLayout list){list.removeAllViews();List<JSONObject> selected=filtered();list.addView(text(selected.size()+" rekod sepadan",12,MUTED,false));gap(list,10);if(selected.isEmpty()){list.addView(text("Tiada rekod. Ubah tapisan atau muatkan data.",16,MUTED,false));return;}int start=page*20;if(start>=selected.size()){page=0;start=0;}for(int i=start;i<Math.min(start+20,selected.size());i++){JSONObject r=selected.get(i);LinearLayout card=card(list,WHITE);card.addView(text(r.optString("tn","Tanaman"),19,INK,true));gap(card,5);card.addView(text(r.optString("l")+" · "+r.optString("d"),14,MUTED,false));gap(card,12);LinearLayout meta=row();meta.addView(text(r.optString("t"),12,MUTED,false),new LinearLayout.LayoutParams(0,-2,1));meta.addView(text(number(r.optDouble("ls",0))+" ha serangan",12,RED,true));card.addView(meta);card.setOnClickListener(v->detail(r,null,false));card.setFocusable(true);card.setContentDescription(r.optString("tn")+", "+r.optString("l")+", buka butiran");}LinearLayout pagination=row();Button prev=button("‹ Sebelum",false,()->{page--;renderRecords(list);});prev.setEnabled(page>0);pagination.addView(prev,new LinearLayout.LayoutParams(0,dp(48),1));Button next=button("Seterusnya ›",false,()->{page++;renderRecords(list);});next.setEnabled((page+1)*20<selected.size());pagination.addView(next,new LinearLayout.LayoutParams(0,dp(48),1));list.addView(pagination);}
    JSONObject normalized(JSONObject row){JSONArray a=array(row,"data");return obj("id",row.optString("row"),"t",a.optString(3),"n",a.optString(4),"d",a.optString(5),"l",a.optString(6),"c",a.optString(7),"kt",a.optString(8),"tn",a.optString(9),"vr",a.optString(10),"um",a.optString(11),"lt",a.optDouble(12,0),"p",a.opt(13),"ps",a.opt(14),"pk",a.opt(15),"s",a.optString(16),"im",a.optString(17),"caption",a.optString(18),"st",a.optString(19),"vb",a.optString(20),"pg",a.optString(1),"em",a.optString(2));}
    boolean supervisor(){return Arrays.asList("ADMIN","PENYELIA").contains(user.optString("role").toUpperCase(Locale.ROOT));}
    void tasks(boolean verify){heading("ALIRAN KERJA",verify?"Pengesahan":"Tugasan saya",verify?"Semak laporan sebelum disahkan":"Draf, laporan baharu dan pembetulan");LinearLayout c=scroller();if(supervisor()){addButton(c,verify?"Lihat tugasan saya":"Semak laporan menunggu",false,()->{epoch++;shell(true);tasks(!verify);});}if(!verify&&!store.get("draft_"+uid).isEmpty())addButton(c,"Sambung draf di telefon",true,()->show("form"));LinearLayout list=column();c.addView(list);list.addView(text("Memuatkan rekod…",14,MUTED,false));request(verify?"data/pending":"data/my-tasks",verify?obj("state",user.optString("state","ALL")):obj("name",user.optString("name")),result->{list.removeAllViews();JSONArray rows=array(result,"rows");list.addView(text(rows.length()+" rekod",14,MUTED,false));gap(list,12);for(int i=0;i<Math.min(rows.length(),100);i++){JSONObject raw=rows.optJSONObject(i);JSONObject r=normalized(raw);LinearLayout card=card(list,WHITE);card.addView(text(r.optString("st","BARU"),12,RED,true));gap(card,7);card.addView(text(r.optString("tn"),18,INK,true));card.addView(text(r.optString("l")+" · "+r.optString("t"),14,MUTED,false));if(!r.optString("vb").isEmpty()){gap(card,8);card.addView(text(r.optString("vb"),14,MUTED,false));}addButton(card,verify?"Semak laporan":"Buka laporan",false,()->detail(r,raw,verify));}if(rows.length()==0)list.addView(text("Tiada tugasan untuk dipaparkan.",16,MUTED,false));if(rows.length()>100)list.addView(text("100 rekod pertama dipaparkan. Gunakan sistem web untuk senarai penuh.",14,MUTED,false));});}
    void detail(JSONObject record,JSONObject raw,boolean verify){final Dialog dialog=new Dialog(this);LinearLayout outer=column();outer.setPadding(dp(22),dp(22),dp(22),dp(22));outer.setBackground(shape(BG,26));ScrollView scroll=new ScrollView(this);LinearLayout c=column();scroll.addView(c);outer.addView(scroll,new LinearLayout.LayoutParams(-1,-1));c.addView(text(record.optString("tn"),25,INK,true));gap(c,5);c.addView(text(record.optString("l"),16,MUTED,false));String[][] values={{"Status",record.optString("st","DISAHKAN")},{"Pegawai",record.optString("pg")},{"Tarikh",record.optString("t")},{"Negeri / daerah",record.optString("n")+" / "+record.optString("d")},{"Luas bertanam",number(record.optDouble("lt",0))+" ha"},{"Varieti / umur",record.optString("vr")+" / "+record.optString("um")},{"Syor kawalan",record.optString("s")},{"Log",record.optString("vb")}};for(String[] v:values){gap(c,16);c.addView(text(v[0],12,MUTED,true));c.addView(text(v[1].isEmpty()?"—":v[1],16,INK,false));}JSONObject pests=object(record,"p");Iterator<String> keys=pests.keys();while(keys.hasNext()){String key=keys.next();gap(c,12);c.addView(text(key+" · "+number(pests.optDouble(key,0))+" ha",16,RED,true));}String coord=record.optString("c");if(coord.matches("\\s*-?\\d+(\\.\\d+)?\\s*,\\s*-?\\d+(\\.\\d+)?\\s*"))addButton(c,"Buka lokasi di peta",false,()->external("geo:"+coord.trim()+"?q="+Uri.encode(coord.trim())));String images=record.optString("im");if(images.startsWith("https://"))addButton(c,"Lihat gambar laporan",false,()->external(images.split(",")[0].trim()));
        if(verify&&supervisor()){addButton(c,"Sahkan laporan",true,()->new AlertDialog.Builder(this).setMessage("Sahkan laporan ini?").setPositiveButton("Sahkan",(d,w)->{dialog.dismiss();request("data/verify",obj("row",record.optString("id"),"act","APPROVE","name",user.optString("name")),r->{toast("Laporan disahkan.");show("tasks");});}).setNegativeButton("Batal",null).show());addButton(c,"Kembalikan untuk pembetulan",false,()->{EditText reason=new EditText(this);reason.setHint("Sebab penolakan");new AlertDialog.Builder(this).setTitle("Sebab pembetulan").setView(reason).setPositiveButton("Hantar",(d,w)->{if(reason.getText().toString().trim().isEmpty()){toast("Sebab diperlukan.");return;}dialog.dismiss();request("data/verify",obj("row",record.optString("id"),"act","REJECT","reason",reason.getText().toString(),"name",user.optString("name")),r->{toast("Laporan dikembalikan.");show("tasks");});}).setNegativeButton("Batal",null).show();});}
        if(raw!=null&&!verify&&Arrays.asList("DRAF","DITOLAK").contains(record.optString("st")))addButton(c,"Edit dan hantar semula",true,()->{dialog.dismiss();editRecord(record);});addButton(c,"Tutup",false,dialog::dismiss);dialog.setContentView(outer);Window window=dialog.getWindow();if(window!=null){window.setBackgroundDrawableResource(android.R.color.transparent);window.setLayout(-1,(int)(getResources().getDisplayMetrics().heightPixels*.88));window.setGravity(Gravity.BOTTOM);}dialog.show();if(window!=null)window.setLayout(-1,(int)(getResources().getDisplayMetrics().heightPixels*.88));}
    void initDraft(){if(draft.length()>0)return;try{draft=new JSONObject(store.get("draft_"+uid));pests=array(draft,"_pests");photos=array(draft,"_photos");editingId=draft.optString("_editingId");retainedImages=array(draft,"_retained");}catch(Exception e){draft=obj("namaPegawai",user.optString("name"),"tarikhBancian",date(),"negeri",user.optString("state").equals("ALL")?"":user.optString("state"));pests=new JSONArray();photos=new JSONArray();editingId="";retainedImages=new JSONArray();}}
    void field(LinearLayout c,String key,String label,boolean numeric){EditText e=input(c,label,draft.optString(key),numeric);fields.put(key,e);}
    void choose(LinearLayout c,String key,String label,List<String> options){field(c,key,label,false);EditText e=fields.get(key);if(!options.isEmpty()){e.setFocusable(false);e.setOnClickListener(v->new AlertDialog.Builder(this).setTitle(label).setItems(options.toArray(new String[0]),(d,n)->{e.setText(options.get(n));collect();if(key.equals("negeri"))put(draft,"daerah","");if(key.equals("kategori"))put(draft,"namaTanaman","");if(key.equals("kategori")||key.equals("namaTanaman")){pests=new JSONArray();put(draft,"_noPest",false);}redrawForm();}).show());}}
    List<String> keys(JSONObject obj){List<String> list=new ArrayList<>();obj.keys().forEachRemaining(list::add);Collections.sort(list);return list;}
    List<String> strings(JSONArray a){List<String> list=new ArrayList<>();for(int i=0;i<a.length();i++)list.add(a.optString(i));return list;}
    void redrawForm(){shell(true);form();}
    void form(){initDraft();fields.clear();heading(editingId.isEmpty()?"BANCIAN BAHARU":"PEMBETULAN LAPORAN","Catat pemerhatian","Langkah "+(step+1)+" daripada 4");LinearLayout c=scroller();LinearLayout steps=row();String[] labels={"Lokasi","Tanaman","Perosak","Semak"};for(int i=0;i<4;i++){TextView t=text((i+1)+"  "+labels[i],12,i==step?INK:MUTED,i==step);t.setBackground(shape(i==step?LIME:BG,12));t.setPadding(dp(7),dp(12),dp(7),dp(12));steps.addView(t,new LinearLayout.LayoutParams(0,-2,1));}c.addView(steps);gap(c,20);LinearLayout panel=card(c,WHITE);
        if(step==0){panel.addView(text("Di mana bancian dibuat?",22,INK,true));field(panel,"namaPegawai","Nama pegawai *",false);fields.get("namaPegawai").setEnabled(false);field(panel,"email","E-mel *",false);fields.get("email").setInputType(33);field(panel,"tarikhBancian","Tarikh bancian *",false);EditText date=fields.get("tarikhBancian");date.setFocusable(false);date.setOnClickListener(v->{Calendar cal=Calendar.getInstance();DatePickerDialog picker=new DatePickerDialog(this,(x,y,m,d)->date.setText(String.format(Locale.US,"%04d-%02d-%02d",y,m+1,d)),cal.get(Calendar.YEAR),cal.get(Calendar.MONTH),cal.get(Calendar.DAY_OF_MONTH));picker.getDatePicker().setMaxDate(System.currentTimeMillis());picker.show();});choose(panel,"negeri","Negeri *",keys(districts));if(!user.optString("state","ALL").equals("ALL"))fields.get("negeri").setEnabled(false);choose(panel,"daerah","Daerah *",strings(array(districts,draft.optString("negeri"))));field(panel,"lokasi","Lokasi / kebun *",false);field(panel,"koordinat","Koordinat latitud, longitud *",false);fields.get("koordinat").setHint("Contoh: 2.9264, 101.6964");addButton(panel,"Gunakan lokasi telefon",false,this::getLocation);panel.addView(text("Pastikan lokasi telefon dihidupkan. Semak ketepatan sebelum menghantar.",12,MUTED,false));}
        if(step==1){panel.addView(text("Maklumat tanaman",22,INK,true));choose(panel,"kategori","Kategori *",keys(master));choose(panel,"namaTanaman","Tanaman *",keys(object(master,draft.optString("kategori"))));field(panel,"varieti","Varieti",false);field(panel,"umurTanaman","Umur tanaman",false);fields.get("umurTanaman").setHint("Contoh: 45 hari");field(panel,"luasBertanam","Luas bertanam (ha) *",true);panel.addView(text("Gunakan hektar. Jangan masukkan bilangan pokok, polibeg atau unit lain.",12,MUTED,false));}
        if(step==2){panel.addView(text("Perosak & kawalan",22,INK,true));CheckBox none=new CheckBox(this);none.setText("Tiada perosak dikesan");none.setTextSize(15);none.setChecked(draft.optBoolean("_noPest"));panel.addView(none);none.setOnCheckedChangeListener((b,checked)->{collect();put(draft,"_noPest",checked);redrawForm();});if(!none.isChecked()){for(int i=0;i<pests.length();i++){final int index=i;JSONObject pest=pests.optJSONObject(i);gap(panel,12);LinearLayout item=card(panel,BG);item.addView(text(pest.optString("name"),18,INK,true));item.addView(text(number(pest.optDouble("area"))+" ha  ·  Tahap "+pest.optInt("severity"),14,MUTED,false));addButton(item,"Buang perosak",false,()->{pests.remove(index);collect();redrawForm();});}addButton(panel,"+ Tambah perosak",false,this::addPest);}field(panel,"syor","Syor kawalan / catatan",false);fields.get("syor").setSingleLine(false);fields.get("syor").setMinLines(3);}
        if(step==3){panel.addView(text("Semak sebelum hantar",22,INK,true));String summary=draft.optString("namaTanaman")+"\n"+draft.optString("lokasi")+"\n"+draft.optString("daerah")+", "+draft.optString("negeri")+"\n"+draft.optString("tarikhBancian")+"\n\nLuas bertanam: "+draft.optString("luasBertanam")+" ha\n"+(draft.optBoolean("_noPest")?"Tiada perosak dikesan":pests.length()+" jenis perosak direkodkan");gap(panel,14);panel.addView(text(summary,16,INK,false));gap(panel,18);panel.addView(text("Gambar lapangan",18,INK,true));panel.addView(text(photos.length()+" gambar baharu · maksimum 4",14,MUTED,false));for(int i=0;i<photos.length();i++){final int index=i;addButton(panel,photos.optJSONObject(i).optString("name")+"  ×",false,()->{photos.remove(index);collect();redrawForm();});}if(retainedImages.length()>0)panel.addView(text(retainedImages.length()+" gambar sedia ada dikekalkan",14,MUTED,false));if(editingId.isEmpty())addButton(panel,"Tambah gambar",false,this::photoMenu);else panel.addView(text("Gambar lama dikekalkan semasa pembetulan. Tambahan gambar untuk rekod lama masih melalui sistem web.",14,MUTED,false));field(panel,"captionGambar","Keterangan gambar",false);}
        LinearLayout actions=row();Button back=button("Kembali",false,()->{collect();step=Math.max(0,step-1);redrawForm();});back.setEnabled(step>0);actions.addView(back,new LinearLayout.LayoutParams(0,dp(52),1));Button next=button(step<3?"Seterusnya  →":"Hantar laporan",true,()->{collect();if(step<3){if(validateStep(step)){step++;saveDraft(false);redrawForm();}}else submit();});LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(0,dp(52),1);lp.leftMargin=dp(10);actions.addView(next,lp);c.addView(actions);addButton(c,"Simpan draf di telefon",false,()->{collect();saveDraft(true);});c.addView(text("Draf telefon belum dihantar ke pelayan.",12,MUTED,false));}
    void collect(){for(Map.Entry<String,EditText> entry:fields.entrySet())put(draft,entry.getKey(),entry.getValue().getText().toString().trim());put(draft,"_pests",pests);put(draft,"_photos",photos);put(draft,"_editingId",editingId);put(draft,"_retained",retainedImages);}
    void saveDraft(boolean notify){if(uid.isEmpty())return;try{store.put("draft_"+uid,draft.toString());if(notify)toast("Draf disimpan pada telefon.");}catch(Exception e){toast("Draf gagal disimpan. Semak ruang telefon.");}}
    boolean validateStep(int current){String[] required=current==0?new String[]{"namaPegawai","email","tarikhBancian","negeri","daerah","lokasi","koordinat"}:current==1?new String[]{"kategori","namaTanaman","luasBertanam"}:new String[]{};for(String key:required)if(draft.optString(key).trim().isEmpty()){if(fields.containsKey(key))fields.get(key).setError("Maklumat diperlukan");toast("Lengkapkan semua maklumat bertanda *.");return false;}if(current==0){if(!android.util.Patterns.EMAIL_ADDRESS.matcher(draft.optString("email")).matches()){toast("E-mel tidak sah.");return false;}try{String[] coord=draft.optString("koordinat").split(",");double lat=Double.parseDouble(coord[0].trim()),lon=Double.parseDouble(coord[1].trim());if(coord.length!=2||!Double.isFinite(lat)||!Double.isFinite(lon)||Math.abs(lat)>90||Math.abs(lon)>180)throw new Exception();}catch(Exception e){toast("Koordinat mesti latitud, longitud yang sah.");return false;}}
        if(current==1&&(!(draft.optDouble("luasBertanam",0)>0)||!Double.isFinite(draft.optDouble("luasBertanam",0)))){toast("Luas bertanam mesti melebihi sifar.");return false;}if(current==2&&!draft.optBoolean("_noPest")&&pests.length()==0){toast("Tambah perosak atau tandakan tiada perosak dikesan.");return false;}if(current==2&&!draft.optBoolean("_noPest")){for(int i=0;i<pests.length();i++)if(pests.optJSONObject(i).optDouble("area")>draft.optDouble("luasBertanam")){toast("Luas serangan perosak melebihi luas bertanam.");return false;}}return true;}
    void addPest(){collect();LinearLayout c=column();c.setPadding(dp(22),dp(12),dp(22),dp(12));AutoCompleteTextView name=new AutoCompleteTextView(this);name.setTextSize(16);name.setHint("Nama perosak");List<String> options=strings(array(object(master,draft.optString("kategori")),draft.optString("namaTanaman")));name.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_dropdown_item_1line,options));name.setThreshold(1);c.addView(name,new LinearLayout.LayoutParams(-1,dp(55)));EditText area=input(c,"Luas serangan (ha)","",true);Spinner severity=new Spinner(this);severity.setAdapter(new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"T1 · Sangat rendah","T2 · Rendah","T3 · Sederhana","T4 · Teruk","T5 · Sangat teruk"}));gap(c,14);c.addView(severity);AlertDialog dialog=new AlertDialog.Builder(this).setTitle("Tambah perosak").setView(c).setPositiveButton("Tambah",null).setNegativeButton("Batal",null).create();dialog.setOnShowListener(v->dialog.getButton(-1).setOnClickListener(w->{String n=name.getText().toString().trim();double a;try{a=Double.parseDouble(area.getText().toString());}catch(Exception e){a=-1;}if(n.isEmpty()||!Double.isFinite(a)||a<0||a>draft.optDouble("luasBertanam",0)){toast("Isi nama dan luas serangan yang sah.");return;}for(int i=0;i<pests.length();i++)if(pests.optJSONObject(i).optString("name").equalsIgnoreCase(n)){toast("Perosak ini sudah ditambah.");return;}pests.put(obj("name",n,"area",a,"severity",severity.getSelectedItemPosition()+1));dialog.dismiss();redrawForm();}));dialog.show();}
    void submit(){if(posting)return;for(int i=0;i<3;i++)if(!validateStep(i)){step=i;redrawForm();return;}new AlertDialog.Builder(this).setTitle("Hantar untuk pengesahan?").setMessage("Semak lokasi, tanaman dan maklumat serangan. Laporan akan dihantar ke sistem v2.").setPositiveButton("Hantar",(d,w)->{posting=true;saveDraft(false);JSONObject payload=new JSONObject();for(String key:new String[]{"namaPegawai","email","tarikhBancian","negeri","daerah","lokasi","koordinat","kategori","namaTanaman","varieti","umurTanaman","luasBertanam","syor","captionGambar"})put(payload,key,draft.optString(key));JSONObject areas=new JSONObject(),percents=new JSONObject(),severity=new JSONObject();List<String> names=new ArrayList<>();if(!draft.optBoolean("_noPest"))for(int i=0;i<pests.length();i++){JSONObject p=pests.optJSONObject(i);String n=p.optString("name");names.add(n);put(areas,n,p.optDouble("area"));put(percents,n,100*p.optDouble("area")/draft.optDouble("luasBertanam"));put(severity,n,p.optInt("severity"));}put(payload,"luasSerangan",areas);put(payload,"peratusSerangan",percents);put(payload,"keterukan",severity);put(payload,"senaraiPerosak",String.join(", ",names));put(payload,"statusRekod","BARU");put(payload,"images",photos.toString());if(!editingId.isEmpty()){put(payload,"row",editingId);put(payload,"retainedImages",retainedImages);put(payload,"newImageLinks",new JSONArray());}request(editingId.isEmpty()?"data/submit-bancian":"data/update-entry",payload,r->{posting=false;store.remove("draft_"+uid);draft=new JSONObject();pests=new JSONArray();photos=new JSONArray();editingId="";step=0;toast("Laporan berjaya dihantar untuk pengesahan.");show("tasks");});}).setNegativeButton("Semak semula",null).show();}
    void editRecord(JSONObject r){fields.clear();draft=obj("namaPegawai",r.optString("pg"),"email",r.optString("em"),"tarikhBancian",r.optString("t").split("T")[0],"negeri",r.optString("n"),"daerah",r.optString("d"),"lokasi",r.optString("l"),"koordinat",r.optString("c"),"kategori",r.optString("kt"),"namaTanaman",r.optString("tn"),"varieti",r.optString("vr"),"umurTanaman",r.optString("um"),"luasBertanam",r.optDouble("lt"),"syor",r.optString("s"),"captionGambar",r.optString("caption"));editingId=r.optString("id");photos=new JSONArray();pests=new JSONArray();retainedImages=new JSONArray();for(String link:r.optString("im").split(","))if(link.trim().startsWith("https://"))retainedImages.put(link.trim());JSONObject area=object(r,"p"),sev=object(r,"pk");Iterator<String> keys=area.keys();while(keys.hasNext()){String n=keys.next();pests.put(obj("name",n,"area",area.optDouble(n),"severity",Math.max(1,Math.min(5,sev.optInt(n,1)))));}put(draft,"_noPest",pests.length()==0);collect();saveDraft(false);step=0;show("form");}
    void getLocation(){if(checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)!=PackageManager.PERMISSION_GRANTED){requestPermissions(new String[]{Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION},31);return;}LocationManager manager=(LocationManager)getSystemService(LOCATION_SERVICE);stopLocation();try{String provider=manager.isProviderEnabled(LocationManager.GPS_PROVIDER)?LocationManager.GPS_PROVIDER:LocationManager.NETWORK_PROVIDER;locationListener=new LocationListener(){public void onLocationChanged(Location l){stopLocation();if(screen.equals("form")&&fields.containsKey("koordinat")){fields.get("koordinat").setText(String.format(Locale.US,"%.6f, %.6f",l.getLatitude(),l.getLongitude()));put(draft,"koordinat",fields.get("koordinat").getText().toString());toast("Ketepatan lokasi: ±"+Math.round(l.getAccuracy())+" meter. Semak sebelum hantar.");}}public void onStatusChanged(String p,int s,Bundle b){}public void onProviderEnabled(String p){}public void onProviderDisabled(String p){}};manager.requestLocationUpdates(provider,1000,0,locationListener,Looper.getMainLooper());toast("Mendapatkan lokasi…");handler.postDelayed(()->{if(locationListener!=null){stopLocation();toast("Lokasi belum diperoleh. Cuba di kawasan terbuka atau isi koordinat manual.");}},20000);}catch(Exception e){stopLocation();toast("Hidupkan lokasi telefon atau isi koordinat manual.");}}
    void stopLocation(){if(locationListener!=null){try{((LocationManager)getSystemService(LOCATION_SERVICE)).removeUpdates(locationListener);}catch(Exception ignored){}locationListener=null;}}
    void photoMenu(){collect();if(photos.length()>=4){toast("Maksimum 4 gambar.");return;}new AlertDialog.Builder(this).setTitle("Gambar lapangan").setItems(new String[]{"Ambil gambar","Pilih gambar"},(d,n)->{if(n==0)camera();else{Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("image/*");startActivityForResult(i,41);}}).show();}
    void camera(){try{ContentValues values=new ContentValues();values.put(MediaStore.Images.Media.DISPLAY_NAME,"PNR-"+System.currentTimeMillis()+".jpg");values.put(MediaStore.Images.Media.MIME_TYPE,"image/jpeg");values.put(MediaStore.Images.Media.RELATIVE_PATH,"Pictures/PNR");cameraUri=getContentResolver().insert(MediaStore.Images.Media.EXTERNAL_CONTENT_URI,values);if(cameraUri==null)throw new IOException();Intent intent=new Intent(MediaStore.ACTION_IMAGE_CAPTURE);intent.putExtra(MediaStore.EXTRA_OUTPUT,cameraUri);intent.addFlags(Intent.FLAG_GRANT_WRITE_URI_PERMISSION|Intent.FLAG_GRANT_READ_URI_PERMISSION);intent.setClipData(ClipData.newRawUri("Gambar PNR",cameraUri));startActivityForResult(intent,42);}catch(Exception e){toast("Kamera tidak tersedia. Pilih gambar dari telefon.");clearPhoto();}}
    void clearPhoto(){if(cameraUri!=null){try{getContentResolver().delete(cameraUri,null,null);}catch(Exception ignored){}cameraUri=null;}}
    void processPhoto(Uri uri){final String owner=uid;final JSONObject target=draft;busy(true);executor.execute(()->{try{Bitmap small=ImageDecoder.decodeBitmap(ImageDecoder.createSource(getContentResolver(),uri),(decoder,info,source)->{int width=info.getSize().getWidth(),height=info.getSize().getHeight();float scale=Math.min(1f,1024f/Math.max(width,height));decoder.setTargetSize(Math.max(1,(int)(width*scale)),Math.max(1,(int)(height*scale)));decoder.setAllocator(ImageDecoder.ALLOCATOR_SOFTWARE);});ByteArrayOutputStream bytes=new ByteArrayOutputStream();small.compress(Bitmap.CompressFormat.JPEG,72,bytes);small.recycle();if(bytes.size()>500000)throw new IOException();String data="data:image/jpeg;base64,"+android.util.Base64.encodeToString(bytes.toByteArray(),android.util.Base64.NO_WRAP);handler.post(()->{if(!uid.equals(owner)||draft!=target)return;photos.put(obj("name","PNR-"+System.currentTimeMillis()+".jpg","dataUrl",data));busy(false);collect();saveDraft(false);if(screen.equals("form"))redrawForm();});}catch(Exception e){handler.post(()->{busy(false);toast("Gambar tidak dapat diproses. Pilih JPEG/PNG lebih kecil.");});}});}
    void profile(){heading("AKAUN & MODUL","Ruang kerja anda",user.optString("role")+" · "+user.optString("state"));LinearLayout c=scroller();LinearLayout card=card(c,INK);card.addView(text(user.optString("name"),24,WHITE,true));gap(card,8);card.addView(text(uid,14,LIME,false));addButton(c,"Sasaran KPI",false,this::kpi);if(user.optString("role").equalsIgnoreCase("ADMIN"))addButton(c,"Senarai pengguna",false,this::users);addButton(c,"RPW & analisis lanjutan — pelayar",false,()->external(ApiClient.ORIGIN+"/rpw.html"));addButton(c,"Sistem web penuh — pelayar",false,()->external(ApiClient.ORIGIN+"/"));gap(c,15);c.addView(text("PNR Native 2.0\nUI Android asli · Sistem percubaan v2",14,MUTED,false));gap(c,8);c.addView(text("Draf telefon disimpan secara setempat. Penghantaran dan pengesahan memerlukan internet.",14,MUTED,false));addButton(c,"Log keluar",false,()->new AlertDialog.Builder(this).setMessage("Log keluar? Draf telefon akaun ini dikekalkan.").setPositiveButton("Log keluar",(d,w)->{store.remove("session");token="";uid="";records=new JSONArray();master=new JSONObject();draft=new JSONObject();pests=new JSONArray();photos=new JSONArray();hasLoaded=false;query="";stateFilter="";showLogin();}).setNegativeButton("Batal",null).show());}
    void kpi(){epoch++;shell(true);heading("SASARAN PEMANTAUAN","Sasaran KPI","Mengikut negeri dan tanaman");LinearLayout c=scroller();addButton(c,"Kembali ke akaun",false,()->show("profile"));request("data/kpi",obj(),r->{JSONObject targets=object(r,"dataSasaran");for(String state:keys(targets)){if(!user.optString("state").equals("ALL")&&!state.equalsIgnoreCase(user.optString("state")))continue;JSONObject crops=object(targets,state);LinearLayout card=card(c,WHITE);card.addView(text(state,20,INK,true));for(String crop:keys(crops)){gap(card,12);card.addView(text(crop,16,INK,false));card.addView(text(number(crops.optDouble(crop))+" ha sasaran",14,MUTED,false));}}});}
    void users(){epoch++;shell(true);heading("PENTADBIRAN","Pengguna","Senarai akaun berdaftar");LinearLayout c=scroller();addButton(c,"Kembali ke akaun",false,()->show("profile"));request("users/list",obj(),r->{JSONArray users=array(r,"users");for(int i=0;i<users.length();i++){JSONObject u=users.optJSONObject(i);LinearLayout card=card(c,WHITE);card.addView(text(u.optString("nama"),18,INK,true));card.addView(text(u.optString("role")+" · "+u.optString("negeri"),14,MUTED,false));card.addView(text(u.optString("status"),14,INK,true));}});}
    String csv(String s){if(s.matches("^[=+@\\t\\r-].*"))s="\'"+s;return "\""+s.replace("\"","\"\"")+"\"";}
    void exportCsv(){StringBuilder b=new StringBuilder("\uFEFFTarikh,Negeri,Daerah,Lokasi,Tanaman,Luas bertanam ha,Luas serangan ha\r\n");for(JSONObject r:filtered()){b.append(csv(r.optString("t"))).append(',').append(csv(r.optString("n"))).append(',').append(csv(r.optString("d"))).append(',').append(csv(r.optString("l"))).append(',').append(csv(r.optString("tn"))).append(',').append(r.optDouble("lt",0)).append(',').append(r.optDouble("ls",0)).append("\r\n");}exportBytes=b.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8);Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.addCategory(Intent.CATEGORY_OPENABLE);i.setType("text/csv");i.putExtra(Intent.EXTRA_TITLE,"PNR-Rekod-"+date()+".csv");startActivityForResult(i,43);}
    void external(String url){Uri uri=Uri.parse(url);if(!Arrays.asList("https","geo").contains(uri.getScheme()))return;try{startActivity(new Intent(Intent.ACTION_VIEW,uri));}catch(Exception e){toast("Tiada aplikasi untuk membuka pautan.");}}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(request==41&&result==RESULT_OK&&data!=null&&data.getData()!=null)processPhoto(data.getData());if(request==42){if(result==RESULT_OK&&cameraUri!=null){Uri uri=cameraUri;cameraUri=null;processPhoto(uri);}else clearPhoto();}if(request==43){byte[] bytes=exportBytes;exportBytes=null;if(result==RESULT_OK&&data!=null&&data.getData()!=null&&bytes!=null){Uri destination=data.getData();executor.execute(()->{try(OutputStream out=getContentResolver().openOutputStream(destination)){if(out==null)throw new IOException();out.write(bytes);handler.post(()->toast("CSV berjaya disimpan."));}catch(Exception e){handler.post(()->toast("Fail gagal disimpan."));}});}}}
    @Override public void onRequestPermissionsResult(int request,String[] permissions,int[] result){super.onRequestPermissionsResult(request,permissions,result);if(request==31){if(checkSelfPermission(Manifest.permission.ACCESS_COARSE_LOCATION)==PackageManager.PERMISSION_GRANTED)getLocation();else toast("Lokasi tidak dibenarkan. Isi koordinat secara manual.");}}
    @Override public void onBackPressed(){if(posting){toast("Tunggu penghantaran selesai dahulu.");return;}if(screen.equals("form")&&step>0){collect();step--;redrawForm();}else if(!screen.equals("home")&&!screen.equals("login"))navigate("home");else new AlertDialog.Builder(this).setMessage("Tutup aplikasi?").setPositiveButton("Tutup",(d,w)->finish()).setNegativeButton("Batal",null).show();}
    @Override protected void onPause(){if(screen.equals("form")){collect();saveDraft(false);}stopLocation();super.onPause();}
    @Override protected void onDestroy(){epoch++;handler.removeCallbacksAndMessages(null);stopLocation();executor.shutdownNow();super.onDestroy();}
    byte[] read(InputStream in)throws IOException{ByteArrayOutputStream out=new ByteArrayOutputStream();byte[] b=new byte[8192];int n;while((n=in.read(b))!=-1)out.write(b,0,n);return out.toByteArray();}
}
