package my.pnr.digital.v2;

import android.app.*;
import android.graphics.*;
import android.net.Uri;
import android.view.*;
import android.widget.*;
import org.json.*;
import java.util.*;

/** Native RPW workspace: filtered snapshots, history, quality checks and correction forms. */
final class RpwModule {
    private final MainActivity a;
    private JSONArray rows=new JSONArray();
    private String owner="",savedAt="",year="",state="",district="",query="",rtd="",tab="Ringkasan";
    private boolean loaded=false,fetching=false,canEdit=false,filtersOpen=false;
    private int page=0;
    RpwModule(MainActivity activity){a=activity;}
    void clear(){rows=new JSONArray();owner="";savedAt="";year="";state="";district="";query="";rtd="";loaded=false;canEdit=false;fetching=false;page=0;}
    void preview(){owner=a.uid;loaded=true;savedAt="Data contoh";for(int i=0;i<8;i++)rows.put(a.obj("row_id","DEMO-"+i,"negeri","SELANGOR","daerah","KUALA SELANGOR","lokasi_pemasangan","Perangkap "+(i+1),"tarikh_kutip",a.date(),"jenis_komoditi","KELAPA","total_catch_rf",i*4,"bil_tangkapan_rv_jantan",i,"status_rtd_rf",i>4?"RTD>1":"RTD=0","lat_long","3."+(300+i*10)+", 101."+(200+i*10)));}
    private void restore(){if(owner.equals(a.uid))return;clear();owner=a.uid;try{JSONObject cached=new JSONObject(a.store.get("rpw_"+owner));rows=a.array(cached,"records");savedAt=cached.optString("savedAt");loaded=true;}catch(Exception ignored){}}
    void show(){restore();a.heading("PEMANTAUAN FEROMON","Perangkap RPW","Tangkapan, trend dan kualiti data");LinearLayout c=a.scroller();
        c.addView(a.text((a.online()?"DALAM TALIAN":"OFFLINE")+"  ·  "+(loaded?"Salinan "+savedAt:"Belum ada salinan data"),12,a.MUTED,false));
        a.addButton(c,fetching?"Sedang memuatkan…":"Segerakkan data RPW",false,this::load);
        a.gap(c,14);LinearLayout tabs=a.row();for(String label:new String[]{"Ringkasan","Perangkap","Audit"}){Button b=a.button(label,tab.equals(label),()->{tab=label;page=0;a.show("rpw");});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,-2,1);p.rightMargin=a.dp(4);tabs.addView(b,p);}c.addView(tabs);
        if(!loaded){a.section(c,"Data RPW belum tersedia","Segerakkan sekali dengan internet. Salinan akan tersedia untuk semakan offline.");if(!fetching)load();return;}
        filters(c);a.gap(c,16);List<JSONObject> history=history();List<JSONObject> latest=RpwData.withStatus(RpwData.latest(history),rtd);
        if(tab.equals("Ringkasan"))overview(c,latest,history);else if(tab.equals("Audit"))audit(c,history);else list(c,latest,false);
        a.addButton(c,"Eksport CSV perangkap ditapis",false,()->export(latest));
        a.addButton(c,"Kembali ke Utama",false,()->a.navigate("home"));
    }
    private List<JSONObject> history(){return RpwData.filter(rows,year,state,district,query);}
    private void filters(LinearLayout c){a.addButton(c,(filtersOpen?"Tutup tapisan":"Tapis data")+"  ·  "+(year.isEmpty()?"Semua tahun":year)+(state.isEmpty()?"":" · "+state)+(rtd.isEmpty()?"":" · "+rtd),false,()->{filtersOpen=!filtersOpen;a.show("rpw");});if(!filtersOpen)return;a.gap(c,12);LinearLayout panel=a.card(c,a.WHITE);panel.addView(a.text("Tapis pemantauan",16,a.INK,true));
        pick(panel,"Tahun",year,values("tarikh_kutip",true),v->{year=v;});
        pick(panel,"Negeri",state,values("negeri",false),v->{state=v;district="";});
        TreeSet<String> districts=new TreeSet<>();for(int i=0;i<rows.length();i++){JSONObject r=rows.optJSONObject(i);if(state.isEmpty()||RpwData.normalized(r,"negeri").equals(state))districts.add(RpwData.normalized(r,"daerah"));}districts.remove("");
        pick(panel,"Daerah",district,new ArrayList<>(districts),v->{district=v;});
        pick(panel,"Status RTD",rtd,Arrays.asList("RTD=0","RTD<1","RTD=1","RTD>1","BELUM DINILAI"),v->{rtd=v;});
        EditText search=a.input(panel,"Lokasi / ID perangkap",query,false);a.addButton(panel,"Cari perangkap",true,()->{query=search.getText().toString().trim();filtersOpen=false;page=0;a.show("rpw");});
        if(!year.isEmpty()||!state.isEmpty()||!district.isEmpty()||!query.isEmpty()||!rtd.isEmpty())a.addButton(panel,"Kosongkan tapisan",false,()->{year="";state="";district="";query="";rtd="";page=0;a.show("rpw");});
    }
    interface Pick{void set(String value);}
    private void pick(LinearLayout c,String label,String selected,List<String> choices,Pick callback){a.addButton(c,label+": "+(selected.isEmpty()?"Semua":selected)+"  ▾",false,()->{List<String> options=new ArrayList<>();options.add("Semua");options.addAll(choices);new AlertDialog.Builder(a).setTitle(label).setItems(options.toArray(new String[0]),(d,n)->{callback.set(n==0?"":options.get(n));page=0;a.show("rpw");}).show();});}
    private List<String> values(String key,boolean date){TreeSet<String> out=new TreeSet<>();for(int i=0;i<rows.length();i++){JSONObject r=rows.optJSONObject(i);String value=RpwData.normalized(r,key);if(date){if(!RpwData.validDate(r))continue;value=RpwData.day(r).substring(0,4);}if(!value.isEmpty())out.add(value);}List<String> list=new ArrayList<>(out);if(date)Collections.reverse(list);return list;}
    void load(){if(a.preview||fetching)return;if(!a.online()){a.toast("Tiada sambungan. Salinan RPW terakhir dikekalkan.");return;}fetching=true;a.busy(true);final String account=a.uid,auth=a.token;
        a.executor.execute(()->{try{JSONArray complete=new JSONArray();boolean more=true,editable=false;int offset=0;while(more){JSONObject response=ApiClient.post("rpw/records",a.obj("offset",offset),auth,account);JSONArray batch=a.array(response,"records");for(int i=0;i<batch.length();i++)complete.put(batch.get(i));editable=response.optBoolean("canEdit");more=response.optBoolean("hasMore");offset+=batch.length();if(more&&(batch.length()==0||offset>=20000))throw new java.io.IOException("Dataset terlalu besar");}final boolean allowed=editable;String time=new java.text.SimpleDateFormat("dd MMM, HH:mm",new Locale("ms","MY")).format(new Date());a.store.put("rpw_"+account,a.obj("records",complete,"savedAt",time).toString());a.handler.post(()->{fetching=false;a.busy(false);if(a.isDestroyed()||!a.uid.equals(account))return;rows=complete;owner=account;loaded=true;canEdit=allowed;savedAt=time;if(a.screen.equals("rpw"))a.show("rpw");});}catch(Exception e){a.handler.post(()->{fetching=false;a.busy(false);if(a.isDestroyed()||!a.uid.equals(account))return;a.alert("RPW belum disegerakkan",e instanceof ApiClient.ApiError?e.getMessage():"Data penuh tidak dapat dimuatkan. Salinan terakhir dikekalkan; cuba lagi dengan sambungan stabil.");});}});
    }
    private int color(JSONObject r){String s=RpwData.status(r);return s.equals("RTD>1")?a.RED:s.equals("RTD=0")?a.TEAL:a.AMBER;}
    private void overview(LinearLayout c,List<JSONObject> latest,List<JSONObject> history){double rf=0,rv=0;int high=0;for(JSONObject r:latest){rf+=RpwData.count(r,"total_catch_rf");rv+=RpwData.rv(r);if(RpwData.status(r).equals("RTD>1"))high++;}
        LinearLayout hero=a.card(c,a.INK);hero.addView(a.text("PERANGKAP DALAM PILIHAN",11,a.LIME,true));a.gap(hero,8);hero.addView(a.text(String.valueOf(latest.size()),42,a.WHITE,true));hero.addView(a.text("Bacaan terkini setiap lokasi dalam tempoh dipilih",14,Color.rgb(189,207,228),false));
        a.section(c,"Tangkapan terkini","RF dan RV mengikut tapisan status RTD");metric(c,"RF",rf,a.TEAL);metric(c,"RV",rv,a.BLUE);metric(c,"Lokasi RTD > 1",high,a.RED);
        a.section(c,"Trend tangkapan RF","Jumlah setiap bulan · semua bacaan dalam tapisan lokasi/tahun");Map<String,Double> monthly=new TreeMap<>();for(JSONObject r:RpwData.withStatus(history,rtd)){if(!RpwData.validDate(r))continue;String month=RpwData.day(r).substring(0,7);monthly.put(month,monthly.getOrDefault(month,0d)+RpwData.count(r,"total_catch_rf"));}bars(c,monthly,a.TEAL);
        a.section(c,"Pengulangan RTD > 1","Bilangan bacaan tinggi mengikut lokasi");Map<String,Double> repeated=new TreeMap<>();for(JSONObject r:history)if(RpwData.status(r).equals("RTD>1")){String loc=RpwData.value(r,"lokasi_pemasangan")+" · "+RpwData.value(r,"daerah");repeated.put(loc,repeated.getOrDefault(loc,0d)+1);}bars(c,repeated,a.RED);
        a.section(c,"Taburan koordinat","Plot GPS native · bukan peta jalan. Buka butiran untuk navigasi.");GpsPlot plot=new GpsPlot(latest);c.addView(plot,new LinearLayout.LayoutParams(-1,a.dp(210)));a.gap(c,16);
    }
    private void metric(LinearLayout c,String label,double value,int color){LinearLayout card=a.card(c,a.WHITE);LinearLayout line=a.row();line.addView(a.text(label,16,a.MUTED,true),new LinearLayout.LayoutParams(0,-2,1));line.addView(a.text(String.format(Locale.US,"%,.0f",value),26,color,true));card.addView(line);}
    private void bars(LinearLayout c,Map<String,Double> data,int color){LinearLayout panel=a.card(c,a.WHITE);if(data.isEmpty()){panel.addView(a.text("Tiada bacaan dalam pilihan ini.",14,a.MUTED,false));return;}double max=Collections.max(data.values());int count=0;for(Map.Entry<String,Double> item:data.entrySet()){if(count++>=24){panel.addView(a.text("24 kumpulan pertama. Kecilkan tempoh untuk butiran.",12,a.MUTED,false));break;}LinearLayout row=a.row();row.addView(a.text(item.getKey(),13,a.INK,false),new LinearLayout.LayoutParams(0,-2,1));row.addView(a.text(String.format(Locale.US,"%,.0f",item.getValue()),13,color,true));panel.addView(row);ProgressBar meter=new ProgressBar(a,null,android.R.attr.progressBarStyleHorizontal);meter.setMax(1000);meter.setProgress((int)(1000*item.getValue()/Math.max(1,max)));meter.setProgressTintList(android.content.res.ColorStateList.valueOf(color));panel.addView(meter,new LinearLayout.LayoutParams(-1,a.dp(10)));a.gap(panel,10);}}
    private void list(LinearLayout c,List<JSONObject> selected,boolean audit){a.section(c,selected.size()+" "+(audit?"rekod perlu disemak":"perangkap"),audit?"Semak punca sebelum membuat pembetulan":"20 perangkap setiap halaman");if(selected.isEmpty()){c.addView(a.text("Tiada rekod sepadan. Ubah tapisan jika perlu.",15,a.MUTED,false));return;}page=Math.max(0,Math.min(page,(selected.size()-1)/20));for(int i=page*20;i<Math.min(selected.size(),page*20+20);i++){JSONObject r=selected.get(i);LinearLayout card=a.card(c,a.WHITE);card.addView(a.text(RpwData.status(r),12,color(r),true));a.gap(card,8);card.addView(a.text(RpwData.value(r,"lokasi_pemasangan"),19,a.INK,true));card.addView(a.text(RpwData.value(r,"daerah")+" · "+RpwData.value(r,"negeri"),13,a.MUTED,false));a.gap(card,12);card.addView(a.text(RpwData.day(r)+"   RF "+RpwData.count(r,"total_catch_rf")+"   RV "+RpwData.rv(r),13,a.INK,true));if(audit)card.addView(a.text(!RpwData.malaysia(r)?"Semak koordinat GPS":!RpwData.validDate(r)?"Tarikh tidak sah":"Kemungkinan rekod berulang",13,a.RED,false));a.addButton(card,"Butiran & sejarah",false,()->detail(r));}
        if(selected.size()<=20)return;LinearLayout controls=a.row();Button prev=a.button("‹ Sebelum",false,()->{page--;a.show("rpw");});prev.setEnabled(page>0);controls.addView(prev,new LinearLayout.LayoutParams(0,-2,1));Button next=a.button("Seterusnya ›",false,()->{page++;a.show("rpw");});next.setEnabled((page+1)*20<selected.size());controls.addView(next,new LinearLayout.LayoutParams(0,-2,1));c.addView(controls);
    }
    private void audit(LinearLayout c,List<JSONObject> history){Map<String,Integer> duplicates=RpwData.duplicates(history);List<JSONObject> issues=new ArrayList<>();for(JSONObject r:RpwData.withStatus(history,rtd))if(!RpwData.malaysia(r)||!RpwData.validDate(r)||RpwData.duplicate(r,duplicates))issues.add(r);c.addView(a.text("Semakan automatik menandakan GPS di luar julat Malaysia, tarikh tidak sah atau lokasi/tarikh berulang. Sahkan di lapangan sebelum memadam.",14,a.MUTED,false));list(c,issues,true);}
    private void detail(JSONObject r){Dialog dialog=new Dialog(a);ScrollView scroll=new ScrollView(a);LinearLayout c=a.column();c.setPadding(a.dp(22),a.dp(22),a.dp(22),a.dp(24));c.setBackgroundColor(a.BG);scroll.addView(c);c.addView(a.text(RpwData.value(r,"lokasi_pemasangan"),25,a.INK,true));c.addView(a.text(RpwData.status(r),14,color(r),true));for(String[] field:new String[][]{{"ID","row_id"},{"Negeri","negeri"},{"Daerah","daerah"},{"Tarikh kutip","tarikh_kutip"},{"Komoditi","jenis_komoditi"},{"Koordinat","lat_long"},{"Tangkapan RF","total_catch_rf"},{"RV jantan","bil_tangkapan_rv_jantan"},{"RV betina","bil_tangkapan_rv_betina"},{"Pokok diserang","bil_pokok_diserang"},{"Pokok ditebang","bil_pokok_ditebang"}}){a.gap(c,12);c.addView(a.text(field[0],12,a.MUTED,true));c.addView(a.text(RpwData.value(r,field[1]).isEmpty()?"—":RpwData.value(r,field[1]),16,a.INK,false));}
        if(RpwData.coordinates(r)!=null)a.addButton(c,"Navigasi ke perangkap",false,()->a.external("geo:"+RpwData.value(r,"lat_long")+"?q="+Uri.encode(RpwData.value(r,"lat_long"))));
        a.section(c,"Sejarah lokasi","Tarikh kutip · RF · RV (semua tahun)");int count=0;for(JSONObject item:RpwData.filter(rows,"","","","")){if(!RpwData.trap(item).equals(RpwData.trap(r)))continue;if(count++>=100){c.addView(a.text("100 bacaan terkini dipaparkan.",12,a.MUTED,false));break;}c.addView(a.text(RpwData.day(item)+"  ·  "+RpwData.count(item,"total_catch_rf")+"  ·  "+RpwData.rv(item),14,a.INK,false));a.gap(c,8);}
        if(a.supervisor()){a.section(c,"Pembetulan rekod","Memerlukan sambungan dan akses pelayan");if(canEdit&&a.online()){a.addButton(c,"Betulkan koordinat GPS",false,()->edit(r,"UPDATE_GPS","Koordinat latitud, longitud",RpwData.value(r,"lat_long"),dialog));a.addButton(c,"Betulkan nama lokasi",false,()->edit(r,"UPDATE_LOCATION","Nama lokasi",RpwData.value(r,"lokasi_pemasangan"),dialog));a.addButton(c,"Padam rekod ini",false,()->new AlertDialog.Builder(a).setTitle("Padam rekod RPW?").setMessage("Rekod "+RpwData.value(r,"row_id")+" di "+RpwData.value(r,"lokasi_pemasangan")+" akan dipadam daripada sumber pusat. Tindakan ini tidak boleh dibatalkan.").setNegativeButton("Batal",null).setPositiveButton("Padam",(d,w)->mutate(r,"DELETE","",dialog)).show());}else c.addView(a.text("Pembetulan belum tersedia. Segerakkan data; jika masih tidak tersedia, hubungi pentadbir.",14,a.MUTED,false));}
        a.addButton(c,"Tutup",false,dialog::dismiss);dialog.setContentView(scroll);dialog.show();dialog.getWindow().setLayout(-1,(int)(a.getResources().getDisplayMetrics().heightPixels*.88));dialog.getWindow().setGravity(Gravity.BOTTOM);
    }
    private void edit(JSONObject r,String action,String label,String value,Dialog parent){LinearLayout c=a.column();c.setPadding(a.dp(20),a.dp(8),a.dp(20),a.dp(16));EditText input=a.input(c,label,value,false);AlertDialog d=new AlertDialog.Builder(a).setTitle(label).setView(c).setNegativeButton("Batal",null).setPositiveButton("Simpan",null).create();d.setOnShowListener(v->d.getButton(-1).setOnClickListener(w->{String s=input.getText().toString().trim();if(s.isEmpty()||(action.equals("UPDATE_GPS")&&RpwData.coordinates(a.obj("lat_long",s))==null)){input.setError("Maklumat tidak sah");return;}d.dismiss();mutate(r,action,s,parent);}));d.show();}
    private void mutate(JSONObject r,String action,String value,Dialog dialog){dialog.dismiss();a.posting=true;a.request("rpw/mutate",a.obj("row_id",RpwData.value(r,"row_id"),"action",action,"value",value),result->{a.posting=false;a.toast("Perubahan diterima. Memuat semula data pusat.");load();});}
    private void export(List<JSONObject> selected){StringBuilder csv=new StringBuilder("\uFEFFID,Tarikh,Negeri,Daerah,Lokasi,Komoditi,RF,RV,Status RTD,Koordinat\r\n");for(JSONObject r:selected){for(String key:new String[]{"row_id","tarikh_kutip","negeri","daerah","lokasi_pemasangan","jenis_komoditi"})csv.append(a.csv(RpwData.value(r,key))).append(',');csv.append(RpwData.count(r,"total_catch_rf")).append(',').append(RpwData.rv(r)).append(',').append(a.csv(RpwData.status(r))).append(',').append(a.csv(RpwData.value(r,"lat_long"))).append("\r\n");}a.saveExport(csv.toString(),"PNR-RPW-"+a.date()+".csv");}
    private final class GpsPlot extends View {
        final List<JSONObject> points;final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG);
        GpsPlot(List<JSONObject> source){super(a);points=new ArrayList<>();for(JSONObject r:source)if(RpwData.malaysia(r))points.add(r);setBackground(a.shape(a.WHITE,18));setContentDescription("Plot koordinat "+points.size()+" perangkap. Lokasi boleh dibuka melalui senarai perangkap.");}
        protected void onDraw(Canvas c){super.onDraw(c);float left=a.dp(28),top=a.dp(24),w=getWidth()-a.dp(56),h=getHeight()-a.dp(54);p.setStrokeWidth(a.dp(1));p.setColor(a.LINE);for(int i=0;i<=4;i++){c.drawLine(left,top+i*h/4,left+w,top+i*h/4,p);c.drawLine(left+i*w/4,top,left+i*w/4,top+h,p);}for(JSONObject r:points){double[] xy=RpwData.coordinates(r);p.setColor(color(r));c.drawCircle(left+(float)((xy[1]-99)/21)*w,top+h-(float)((xy[0]-.8)/6.7)*h,a.dp(4),p);}p.setColor(a.MUTED);p.setTextSize(a.dp(11));c.drawText(points.isEmpty()?"Tiada koordinat sah":"99° E                         Longitud                         120° E",left,getHeight()-a.dp(10),p);}
    }
}
