-- Reviewed against actual public.Data/public.user schema, 2026-09-14.
-- NOT YET APPLIED. Verify server service-role key and signing secret first.
-- Duplicate login identities must be resolved by the owner. No name-based ownership backfill.
BEGIN;
DO $$ BEGIN
  IF to_regclass('public."Data"') IS NULL OR to_regclass('public."user"') IS NULL THEN
    RAISE EXCEPTION 'Expected production tables public.Data and public.user; inspect schema first';
  END IF;
  IF EXISTS (SELECT 1 FROM public."user" GROUP BY lower(trim(uid)) HAVING count(*) > 1) THEN
    RAISE EXCEPTION 'Duplicate login IDs require owner review before deployment';
  END IF;
  IF EXISTS (SELECT 1 FROM public."user" WHERE uid IS NULL OR trim(uid)='') THEN
    RAISE EXCEPTION 'Empty login IDs require owner review before deployment';
  END IF;
END $;
ALTER TABLE public."user" ADD COLUMN IF NOT EXISTS id bigint GENERATED BY DEFAULT AS IDENTITY;
ALTER TABLE public."user" ADD COLUMN IF NOT EXISTS created_at timestamptz;
CREATE UNIQUE INDEX IF NOT EXISTS pnr_user_id ON public."user"(id);
CREATE UNIQUE INDEX IF NOT EXISTS pnr_user_login ON public."user"(lower(trim(uid)));
ALTER TABLE public."Data" ADD COLUMN IF NOT EXISTS uid text;
ALTER TABLE public."Data" ADD COLUMN IF NOT EXISTS created_at timestamptz;
ALTER TABLE public."Data" ADD COLUMN IF NOT EXISTS submission_id text;
ALTER TABLE public."Data" ADD COLUMN IF NOT EXISTS submission_hash text;
CREATE UNIQUE INDEX IF NOT EXISTS data_submission_once ON public."Data" (uid, submission_id) WHERE submission_id IS NOT NULL;
-- Custom API sessions are verified by the server, not Supabase Auth JWTs.
-- Browser/mobile clients must have no direct table privileges.
REVOKE ALL ON public."Data", public."user" FROM anon, authenticated;
ALTER TABLE public."Data" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."user" ENABLE ROW LEVEL SECURITY;

CREATE TABLE IF NOT EXISTS public.session_logs (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 user_name text,user_role text,login_at timestamptz DEFAULT now(),ip_address text
);
CREATE TABLE IF NOT EXISTS public.ignored_redundant (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 record_id text NOT NULL UNIQUE REFERENCES public."Data"(id) ON DELETE CASCADE,
 ignored_by text,ignored_at timestamptz DEFAULT now()
);
CREATE TABLE IF NOT EXISTS public.sasaran_kpi (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 negeri text NOT NULL,tanaman text NOT NULL,
 sasaran_ha numeric(12,4) NOT NULL CHECK(sasaran_ha>=0),
 tahun integer NOT NULL,UNIQUE(negeri,tanaman,tahun)
);
CREATE TABLE IF NOT EXISTS public.tanaman_tumpuan (
 id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 negeri text NOT NULL,tanaman text NOT NULL,aktif boolean NOT NULL DEFAULT true,
 UNIQUE(negeri,tanaman)
);
ALTER TABLE public."Pest_list" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.session_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.ignored_redundant ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sasaran_kpi ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tanaman_tumpuan ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public."Data",public."user",public."Pest_list",public.session_logs,
 public.ignored_redundant,public.sasaran_kpi,public.tanaman_tumpuan FROM PUBLIC,anon,authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON public."Data",public."user",public."Pest_list",
 public.session_logs,public.ignored_redundant,public.sasaran_kpi,public.tanaman_tumpuan TO service_role;
GRANT USAGE,SELECT ON SEQUENCE public.user_id_seq,public.session_logs_id_seq,
 public.ignored_redundant_id_seq,public.sasaran_kpi_id_seq,public.tanaman_tumpuan_id_seq TO service_role;
CREATE INDEX IF NOT EXISTS pnr_data_scope_status ON public."Data"(negeri,status);
CREATE INDEX IF NOT EXISTS pnr_data_owner_status ON public."Data"(uid,status);

CREATE TABLE IF NOT EXISTS public.pnr_auth_attempts (
  bucket text PRIMARY KEY,
  attempts integer NOT NULL,
  expires_at timestamptz NOT NULL
);
ALTER TABLE public.pnr_auth_attempts ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.pnr_auth_attempts FROM PUBLIC, anon, authenticated;
GRANT SELECT,INSERT,UPDATE,DELETE ON public.pnr_auth_attempts TO service_role;
CREATE OR REPLACE FUNCTION public.pnr_take_auth_attempt(bucket_key text,max_attempts integer)
RETURNS boolean LANGUAGE plpgsql SECURITY INVOKER SET search_path = public, pg_temp AS $$
DECLARE count_now integer;
BEGIN
  IF length(bucket_key) <> 64 OR max_attempts NOT BETWEEN 1 AND 100 THEN RETURN false; END IF;
  INSERT INTO public.pnr_auth_attempts(bucket,attempts,expires_at)
  VALUES(bucket_key,1,now()+interval '15 minutes')
  ON CONFLICT(bucket) DO UPDATE SET
    attempts=CASE WHEN pnr_auth_attempts.expires_at<=now() THEN 1 ELSE pnr_auth_attempts.attempts+1 END,
    expires_at=CASE WHEN pnr_auth_attempts.expires_at<=now() THEN now()+interval '15 minutes' ELSE pnr_auth_attempts.expires_at END
  RETURNING attempts INTO count_now;
  DELETE FROM public.pnr_auth_attempts WHERE expires_at < now()-interval '1 day';
  RETURN count_now<=max_attempts;
END $$;
REVOKE ALL ON FUNCTION public.pnr_take_auth_attempt(text,integer) FROM PUBLIC,anon,authenticated;
GRANT EXECUTE ON FUNCTION public.pnr_take_auth_attempt(text,integer) TO service_role;
COMMIT;
